/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Quiziset API
 * The RESTful APIs Docs for the Quiziset app
 * OpenAPI spec version: 1.0
 */
import { useMutation } from '@tanstack/react-query'
import type { MutationFunction, QueryClient, UseMutationOptions, UseMutationResult } from '@tanstack/react-query'

import type { AuthToken, LoginDto, SignupDto } from './model'

export type signupResponse201 = {
  data: AuthToken
  status: 201
}

export type signupResponse400 = {
  data: void
  status: 400
}

export type signupResponse422 = {
  data: void
  status: 422
}

export type signupResponse500 = {
  data: void
  status: 500
}

export type signupResponseSuccess = signupResponse201 & {
  headers: Headers
}
export type signupResponseError = (signupResponse400 | signupResponse422 | signupResponse500) & {
  headers: Headers
}

export const getSignupUrl = () => {
  return `http://localhost:4004/auth/signup`
}

/**
 * @summary Registers a new user
 */
export const signup = async (signupDto: SignupDto, options?: RequestInit): Promise<signupResponseSuccess> => {
  const res = await fetch(getSignupUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(signupDto),
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  if (!res.ok) {
    const err: globalThis.Error & { info?: signupResponseError['data']; status?: number } = new globalThis.Error()
    const data: signupResponseError['data'] = body ? JSON.parse(body) : {}
    err.info = data
    err.status = res.status
    throw err
  }
  const data: signupResponseSuccess['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as signupResponseSuccess
}

export const getSignupMutationOptions = <TError = void, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof signup>>, TError, { data: SignupDto }, TContext>
  fetch?: RequestInit
}): UseMutationOptions<Awaited<ReturnType<typeof signup>>, TError, { data: SignupDto }, TContext> => {
  const mutationKey = ['signup']
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined }

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof signup>>, { data: SignupDto }> = (props) => {
    const { data } = props ?? {}

    return signup(data, fetchOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type SignupMutationResult = NonNullable<Awaited<ReturnType<typeof signup>>>
export type SignupMutationBody = SignupDto
export type SignupMutationError = void

/**
 * @summary Registers a new user
 */
export const useSignup = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof signup>>, TError, { data: SignupDto }, TContext>
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof signup>>, TError, { data: SignupDto }, TContext> => {
  return useMutation(getSignupMutationOptions(options), queryClient)
}
export type loginResponse200 = {
  data: AuthToken
  status: 200
}

export type loginResponse401 = {
  data: void
  status: 401
}

export type loginResponse500 = {
  data: void
  status: 500
}

export type loginResponseSuccess = loginResponse200 & {
  headers: Headers
}
export type loginResponseError = (loginResponse401 | loginResponse500) & {
  headers: Headers
}

export const getLoginUrl = () => {
  return `http://localhost:4004/auth/login`
}

/**
 * @summary Logins User
 */
export const login = async (loginDto: LoginDto, options?: RequestInit): Promise<loginResponseSuccess> => {
  const res = await fetch(getLoginUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(loginDto),
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  if (!res.ok) {
    const err: globalThis.Error & { info?: loginResponseError['data']; status?: number } = new globalThis.Error()
    const data: loginResponseError['data'] = body ? JSON.parse(body) : {}
    err.info = data
    err.status = res.status
    throw err
  }
  const data: loginResponseSuccess['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as loginResponseSuccess
}

export const getLoginMutationOptions = <TError = void, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof login>>, TError, { data: LoginDto }, TContext>
  fetch?: RequestInit
}): UseMutationOptions<Awaited<ReturnType<typeof login>>, TError, { data: LoginDto }, TContext> => {
  const mutationKey = ['login']
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined }

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof login>>, { data: LoginDto }> = (props) => {
    const { data } = props ?? {}

    return login(data, fetchOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type LoginMutationResult = NonNullable<Awaited<ReturnType<typeof login>>>
export type LoginMutationBody = LoginDto
export type LoginMutationError = void

/**
 * @summary Logins User
 */
export const useLogin = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof login>>, TError, { data: LoginDto }, TContext>
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof login>>, TError, { data: LoginDto }, TContext> => {
  return useMutation(getLoginMutationOptions(options), queryClient)
}
