/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Quiziset API
 * The RESTful APIs Docs for the Quiziset app
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query'

import type { CreateQuizDto, GetAllParams, QuizEntity, UpdateQuizDto } from './model'

export type getAllResponse200 = {
  data: QuizEntity[]
  status: 200
}

export type getAllResponse401 = {
  data: void
  status: 401
}

export type getAllResponse500 = {
  data: void
  status: 500
}

export type getAllResponseSuccess = getAllResponse200 & {
  headers: Headers
}
export type getAllResponseError = (getAllResponse401 | getAllResponse500) & {
  headers: Headers
}

export const getGetAllUrl = (params?: GetAllParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `http://localhost:4004/quizzes?${stringifiedParams}`
    : `http://localhost:4004/quizzes`
}

/**
 * @summary get all public quizzes, or own quizzes when managedByMe=true (latter case requires auth)
 */
export const getAll = async (params?: GetAllParams, options?: RequestInit): Promise<getAllResponseSuccess> => {
  const res = await fetch(getGetAllUrl(params), {
    ...options,
    method: 'GET',
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  if (!res.ok) {
    const err: globalThis.Error & { info?: getAllResponseError['data']; status?: number } = new globalThis.Error()
    const data: getAllResponseError['data'] = body ? JSON.parse(body) : {}
    err.info = data
    err.status = res.status
    throw err
  }
  const data: getAllResponseSuccess['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getAllResponseSuccess
}

export const getGetAllQueryKey = (params?: GetAllParams) => {
  return [`http://localhost:4004/quizzes`, ...(params ? [params] : [])] as const
}

export const getGetAllQueryOptions = <TData = Awaited<ReturnType<typeof getAll>>, TError = void>(
  params?: GetAllParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAll>>, TError, TData>>
    fetch?: RequestInit
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetAllQueryKey(params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAll>>> = ({ signal }) =>
    getAll(params, { signal, ...fetchOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAll>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAllQueryResult = NonNullable<Awaited<ReturnType<typeof getAll>>>
export type GetAllQueryError = void

export function useGetAll<TData = Awaited<ReturnType<typeof getAll>>, TError = void>(
  params: undefined | GetAllParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAll>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<Awaited<ReturnType<typeof getAll>>, TError, Awaited<ReturnType<typeof getAll>>>,
        'initialData'
      >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAll<TData = Awaited<ReturnType<typeof getAll>>, TError = void>(
  params?: GetAllParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAll>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<Awaited<ReturnType<typeof getAll>>, TError, Awaited<ReturnType<typeof getAll>>>,
        'initialData'
      >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAll<TData = Awaited<ReturnType<typeof getAll>>, TError = void>(
  params?: GetAllParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAll>>, TError, TData>>
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary get all public quizzes, or own quizzes when managedByMe=true (latter case requires auth)
 */

export function useGetAll<TData = Awaited<ReturnType<typeof getAll>>, TError = void>(
  params?: GetAllParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAll>>, TError, TData>>
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetAllQueryOptions(params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  return { ...query, queryKey: queryOptions.queryKey }
}

export type createResponse201 = {
  data: QuizEntity
  status: 201
}

export type createResponse401 = {
  data: void
  status: 401
}

export type createResponse422 = {
  data: void
  status: 422
}

export type createResponse500 = {
  data: void
  status: 500
}

export type createResponseSuccess = createResponse201 & {
  headers: Headers
}
export type createResponseError = (createResponse401 | createResponse422 | createResponse500) & {
  headers: Headers
}

export const getCreateUrl = () => {
  return `http://localhost:4004/quizzes`
}

/**
 * @summary create a new quiz
 */
export const create = async (createQuizDto: CreateQuizDto, options?: RequestInit): Promise<createResponseSuccess> => {
  const res = await fetch(getCreateUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createQuizDto),
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  if (!res.ok) {
    const err: globalThis.Error & { info?: createResponseError['data']; status?: number } = new globalThis.Error()
    const data: createResponseError['data'] = body ? JSON.parse(body) : {}
    err.info = data
    err.status = res.status
    throw err
  }
  const data: createResponseSuccess['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createResponseSuccess
}

export const getCreateMutationOptions = <TError = void, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof create>>, TError, { data: CreateQuizDto }, TContext>
  fetch?: RequestInit
}): UseMutationOptions<Awaited<ReturnType<typeof create>>, TError, { data: CreateQuizDto }, TContext> => {
  const mutationKey = ['create']
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined }

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof create>>, { data: CreateQuizDto }> = (props) => {
    const { data } = props ?? {}

    return create(data, fetchOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type CreateMutationResult = NonNullable<Awaited<ReturnType<typeof create>>>
export type CreateMutationBody = CreateQuizDto
export type CreateMutationError = void

/**
 * @summary create a new quiz
 */
export const useCreate = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof create>>, TError, { data: CreateQuizDto }, TContext>
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof create>>, TError, { data: CreateQuizDto }, TContext> => {
  return useMutation(getCreateMutationOptions(options), queryClient)
}
export type getResponse200 = {
  data: QuizEntity
  status: 200
}

export type getResponse403 = {
  data: void
  status: 403
}

export type getResponse404 = {
  data: void
  status: 404
}

export type getResponse500 = {
  data: void
  status: 500
}

export type getResponseSuccess = getResponse200 & {
  headers: Headers
}
export type getResponseError = (getResponse403 | getResponse404 | getResponse500) & {
  headers: Headers
}

export const getGetUrl = (id: number) => {
  return `http://localhost:4004/quizzes/${id}`
}

/**
 * @summary get a quiz by id
 */
export const get = async (id: number, options?: RequestInit): Promise<getResponseSuccess> => {
  const res = await fetch(getGetUrl(id), {
    ...options,
    method: 'GET',
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  if (!res.ok) {
    const err: globalThis.Error & { info?: getResponseError['data']; status?: number } = new globalThis.Error()
    const data: getResponseError['data'] = body ? JSON.parse(body) : {}
    err.info = data
    err.status = res.status
    throw err
  }
  const data: getResponseSuccess['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getResponseSuccess
}

export const getGetQueryKey = (id: number) => {
  return [`http://localhost:4004/quizzes/${id}`] as const
}

export const getGetQueryOptions = <TData = Awaited<ReturnType<typeof get>>, TError = void>(
  id: number,
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof get>>, TError, TData>>; fetch?: RequestInit },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetQueryKey(id)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof get>>> = ({ signal }) => get(id, { signal, ...fetchOptions })

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof get>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetQueryResult = NonNullable<Awaited<ReturnType<typeof get>>>
export type GetQueryError = void

export function useGet<TData = Awaited<ReturnType<typeof get>>, TError = void>(
  id: number,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof get>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<Awaited<ReturnType<typeof get>>, TError, Awaited<ReturnType<typeof get>>>,
        'initialData'
      >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGet<TData = Awaited<ReturnType<typeof get>>, TError = void>(
  id: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof get>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<Awaited<ReturnType<typeof get>>, TError, Awaited<ReturnType<typeof get>>>,
        'initialData'
      >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGet<TData = Awaited<ReturnType<typeof get>>, TError = void>(
  id: number,
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof get>>, TError, TData>>; fetch?: RequestInit },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary get a quiz by id
 */

export function useGet<TData = Awaited<ReturnType<typeof get>>, TError = void>(
  id: number,
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof get>>, TError, TData>>; fetch?: RequestInit },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetQueryOptions(id, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  return { ...query, queryKey: queryOptions.queryKey }
}

export type updateResponse200 = {
  data: QuizEntity
  status: 200
}

export type updateResponse401 = {
  data: void
  status: 401
}

export type updateResponse403 = {
  data: void
  status: 403
}

export type updateResponse404 = {
  data: void
  status: 404
}

export type updateResponse422 = {
  data: void
  status: 422
}

export type updateResponse500 = {
  data: void
  status: 500
}

export type updateResponseSuccess = updateResponse200 & {
  headers: Headers
}
export type updateResponseError = (
  | updateResponse401
  | updateResponse403
  | updateResponse404
  | updateResponse422
  | updateResponse500
) & {
  headers: Headers
}

export const getUpdateUrl = (id: number) => {
  return `http://localhost:4004/quizzes/${id}`
}

/**
 * @summary update a quiz
 */
export const update = async (
  id: number,
  updateQuizDto: UpdateQuizDto,
  options?: RequestInit,
): Promise<updateResponseSuccess> => {
  const res = await fetch(getUpdateUrl(id), {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateQuizDto),
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  if (!res.ok) {
    const err: globalThis.Error & { info?: updateResponseError['data']; status?: number } = new globalThis.Error()
    const data: updateResponseError['data'] = body ? JSON.parse(body) : {}
    err.info = data
    err.status = res.status
    throw err
  }
  const data: updateResponseSuccess['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as updateResponseSuccess
}

export const getUpdateMutationOptions = <TError = void, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof update>>,
    TError,
    { id: number; data: UpdateQuizDto },
    TContext
  >
  fetch?: RequestInit
}): UseMutationOptions<Awaited<ReturnType<typeof update>>, TError, { id: number; data: UpdateQuizDto }, TContext> => {
  const mutationKey = ['update']
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined }

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof update>>, { id: number; data: UpdateQuizDto }> = (
    props,
  ) => {
    const { id, data } = props ?? {}

    return update(id, data, fetchOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type UpdateMutationResult = NonNullable<Awaited<ReturnType<typeof update>>>
export type UpdateMutationBody = UpdateQuizDto
export type UpdateMutationError = void

/**
 * @summary update a quiz
 */
export const useUpdate = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof update>>,
      TError,
      { id: number; data: UpdateQuizDto },
      TContext
    >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof update>>, TError, { id: number; data: UpdateQuizDto }, TContext> => {
  return useMutation(getUpdateMutationOptions(options), queryClient)
}
export type _deleteResponse200 = {
  data: void
  status: 200
}

export type _deleteResponse401 = {
  data: void
  status: 401
}

export type _deleteResponse403 = {
  data: void
  status: 403
}

export type _deleteResponse404 = {
  data: void
  status: 404
}

export type _deleteResponse500 = {
  data: void
  status: 500
}

export type _deleteResponseSuccess = _deleteResponse200 & {
  headers: Headers
}
export type _deleteResponseError = (
  | _deleteResponse401
  | _deleteResponse403
  | _deleteResponse404
  | _deleteResponse500
) & {
  headers: Headers
}

export const getDeleteUrl = (id: number) => {
  return `http://localhost:4004/quizzes/${id}`
}

/**
 * @summary delete a quiz
 */
export const _delete = async (id: number, options?: RequestInit): Promise<_deleteResponseSuccess> => {
  const res = await fetch(getDeleteUrl(id), {
    ...options,
    method: 'DELETE',
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  if (!res.ok) {
    const err: globalThis.Error & { info?: _deleteResponseError['data']; status?: number } = new globalThis.Error()
    const data: _deleteResponseError['data'] = body ? JSON.parse(body) : {}
    err.info = data
    err.status = res.status
    throw err
  }
  const data: _deleteResponseSuccess['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as _deleteResponseSuccess
}

export const getDeleteMutationOptions = <TError = void, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof _delete>>, TError, { id: number }, TContext>
  fetch?: RequestInit
}): UseMutationOptions<Awaited<ReturnType<typeof _delete>>, TError, { id: number }, TContext> => {
  const mutationKey = ['_delete']
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined }

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof _delete>>, { id: number }> = (props) => {
    const { id } = props ?? {}

    return _delete(id, fetchOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type _DeleteMutationResult = NonNullable<Awaited<ReturnType<typeof _delete>>>

export type _DeleteMutationError = void

/**
 * @summary delete a quiz
 */
export const useDelete = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof _delete>>, TError, { id: number }, TContext>
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof _delete>>, TError, { id: number }, TContext> => {
  return useMutation(getDeleteMutationOptions(options), queryClient)
}
