/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Quiziset API
 * The RESTful APIs Docs for the Quiziset app
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query'

import type {
  CreateQuizDto,
  ErrorResponse,
  GetAllQuizzesParams,
  QuizEntity,
  QuizSessionStateEntity,
  StartQuizSessionDto,
  SubmitQuizSessionAnswerDto,
  UpdateQuizDto,
} from './model'

import { customFetch } from '../utils/orval-custom-fetch'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

export type getAllQuizzesResponse200 = {
  data: QuizEntity[]
  status: 200
}

export type getAllQuizzesResponse401 = {
  data: ErrorResponse
  status: 401
}

export type getAllQuizzesResponse500 = {
  data: ErrorResponse
  status: 500
}

export type getAllQuizzesResponseSuccess = getAllQuizzesResponse200 & {
  headers: Headers
}
export type getAllQuizzesResponseError = (getAllQuizzesResponse401 | getAllQuizzesResponse500) & {
  headers: Headers
}

export type getAllQuizzesResponse = getAllQuizzesResponseSuccess | getAllQuizzesResponseError

export const getGetAllQuizzesUrl = (params?: GetAllQuizzesParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0 ? `/quizzes?${stringifiedParams}` : `/quizzes`
}

/**
 * @summary get all public quizzes, or own quizzes when managedByMe=true (latter case requires auth)
 */
export const getAllQuizzes = async (
  params?: GetAllQuizzesParams,
  options?: RequestInit,
): Promise<getAllQuizzesResponse> => {
  return customFetch<getAllQuizzesResponse>(getGetAllQuizzesUrl(params), {
    ...options,
    method: 'GET',
  })
}

export const getGetAllQuizzesQueryKey = (params?: GetAllQuizzesParams) => {
  return [`/quizzes`, ...(params ? [params] : [])] as const
}

export const getGetAllQuizzesQueryOptions = <TData = Awaited<ReturnType<typeof getAllQuizzes>>, TError = ErrorResponse>(
  params?: GetAllQuizzesParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllQuizzes>>, TError, TData>>
    request?: SecondParameter<typeof customFetch>
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetAllQuizzesQueryKey(params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllQuizzes>>> = ({ signal }) =>
    getAllQuizzes(params, { signal, ...requestOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAllQuizzes>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAllQuizzesQueryResult = NonNullable<Awaited<ReturnType<typeof getAllQuizzes>>>
export type GetAllQuizzesQueryError = ErrorResponse

export function useGetAllQuizzes<TData = Awaited<ReturnType<typeof getAllQuizzes>>, TError = ErrorResponse>(
  params: undefined | GetAllQuizzesParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllQuizzes>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllQuizzes>>,
          TError,
          Awaited<ReturnType<typeof getAllQuizzes>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllQuizzes<TData = Awaited<ReturnType<typeof getAllQuizzes>>, TError = ErrorResponse>(
  params?: GetAllQuizzesParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllQuizzes>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllQuizzes>>,
          TError,
          Awaited<ReturnType<typeof getAllQuizzes>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllQuizzes<TData = Awaited<ReturnType<typeof getAllQuizzes>>, TError = ErrorResponse>(
  params?: GetAllQuizzesParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllQuizzes>>, TError, TData>>
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary get all public quizzes, or own quizzes when managedByMe=true (latter case requires auth)
 */

export function useGetAllQuizzes<TData = Awaited<ReturnType<typeof getAllQuizzes>>, TError = ErrorResponse>(
  params?: GetAllQuizzesParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllQuizzes>>, TError, TData>>
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetAllQuizzesQueryOptions(params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  return { ...query, queryKey: queryOptions.queryKey }
}

/**
 * @summary get all public quizzes, or own quizzes when managedByMe=true (latter case requires auth)
 */
export const prefetchGetAllQuizzesQuery = async <
  TData = Awaited<ReturnType<typeof getAllQuizzes>>,
  TError = ErrorResponse,
>(
  queryClient: QueryClient,
  params?: GetAllQuizzesParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllQuizzes>>, TError, TData>>
    request?: SecondParameter<typeof customFetch>
  },
): Promise<QueryClient> => {
  const queryOptions = getGetAllQuizzesQueryOptions(params, options)

  await queryClient.prefetchQuery(queryOptions)

  return queryClient
}

export type createQuizResponse201 = {
  data: QuizEntity
  status: 201
}

export type createQuizResponse401 = {
  data: ErrorResponse
  status: 401
}

export type createQuizResponse422 = {
  data: ErrorResponse
  status: 422
}

export type createQuizResponse500 = {
  data: ErrorResponse
  status: 500
}

export type createQuizResponseSuccess = createQuizResponse201 & {
  headers: Headers
}
export type createQuizResponseError = (createQuizResponse401 | createQuizResponse422 | createQuizResponse500) & {
  headers: Headers
}

export type createQuizResponse = createQuizResponseSuccess | createQuizResponseError

export const getCreateQuizUrl = () => {
  return `/quizzes`
}

/**
 * @summary create a new quiz
 */
export const createQuiz = async (createQuizDto: CreateQuizDto, options?: RequestInit): Promise<createQuizResponse> => {
  return customFetch<createQuizResponse>(getCreateQuizUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createQuizDto),
  })
}

export const getCreateQuizMutationOptions = <TError = ErrorResponse, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof createQuiz>>, TError, { data: CreateQuizDto }, TContext>
  request?: SecondParameter<typeof customFetch>
}): UseMutationOptions<Awaited<ReturnType<typeof createQuiz>>, TError, { data: CreateQuizDto }, TContext> => {
  const mutationKey = ['createQuiz']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof createQuiz>>, { data: CreateQuizDto }> = (props) => {
    const { data } = props ?? {}

    return createQuiz(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type CreateQuizMutationResult = NonNullable<Awaited<ReturnType<typeof createQuiz>>>
export type CreateQuizMutationBody = CreateQuizDto
export type CreateQuizMutationError = ErrorResponse

/**
 * @summary create a new quiz
 */
export const useCreateQuiz = <TError = ErrorResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof createQuiz>>, TError, { data: CreateQuizDto }, TContext>
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof createQuiz>>, TError, { data: CreateQuizDto }, TContext> => {
  return useMutation(getCreateQuizMutationOptions(options), queryClient)
}
export type getSingleQuizResponse200 = {
  data: QuizEntity
  status: 200
}

export type getSingleQuizResponse403 = {
  data: ErrorResponse
  status: 403
}

export type getSingleQuizResponse404 = {
  data: ErrorResponse
  status: 404
}

export type getSingleQuizResponse500 = {
  data: ErrorResponse
  status: 500
}

export type getSingleQuizResponseSuccess = getSingleQuizResponse200 & {
  headers: Headers
}
export type getSingleQuizResponseError = (
  | getSingleQuizResponse403
  | getSingleQuizResponse404
  | getSingleQuizResponse500
) & {
  headers: Headers
}

export type getSingleQuizResponse = getSingleQuizResponseSuccess | getSingleQuizResponseError

export const getGetSingleQuizUrl = (id: number) => {
  return `/quizzes/${id}`
}

/**
 * @summary get a quiz by id
 */
export const getSingleQuiz = async (id: number, options?: RequestInit): Promise<getSingleQuizResponse> => {
  return customFetch<getSingleQuizResponse>(getGetSingleQuizUrl(id), {
    ...options,
    method: 'GET',
  })
}

export const getGetSingleQuizQueryKey = (id: number) => {
  return [`/quizzes/${id}`] as const
}

export const getGetSingleQuizQueryOptions = <TData = Awaited<ReturnType<typeof getSingleQuiz>>, TError = ErrorResponse>(
  id: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSingleQuiz>>, TError, TData>>
    request?: SecondParameter<typeof customFetch>
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetSingleQuizQueryKey(id)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getSingleQuiz>>> = ({ signal }) =>
    getSingleQuiz(id, { signal, ...requestOptions })

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getSingleQuiz>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetSingleQuizQueryResult = NonNullable<Awaited<ReturnType<typeof getSingleQuiz>>>
export type GetSingleQuizQueryError = ErrorResponse

export function useGetSingleQuiz<TData = Awaited<ReturnType<typeof getSingleQuiz>>, TError = ErrorResponse>(
  id: number,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSingleQuiz>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSingleQuiz>>,
          TError,
          Awaited<ReturnType<typeof getSingleQuiz>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSingleQuiz<TData = Awaited<ReturnType<typeof getSingleQuiz>>, TError = ErrorResponse>(
  id: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSingleQuiz>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSingleQuiz>>,
          TError,
          Awaited<ReturnType<typeof getSingleQuiz>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSingleQuiz<TData = Awaited<ReturnType<typeof getSingleQuiz>>, TError = ErrorResponse>(
  id: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSingleQuiz>>, TError, TData>>
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary get a quiz by id
 */

export function useGetSingleQuiz<TData = Awaited<ReturnType<typeof getSingleQuiz>>, TError = ErrorResponse>(
  id: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSingleQuiz>>, TError, TData>>
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetSingleQuizQueryOptions(id, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  return { ...query, queryKey: queryOptions.queryKey }
}

/**
 * @summary get a quiz by id
 */
export const prefetchGetSingleQuizQuery = async <
  TData = Awaited<ReturnType<typeof getSingleQuiz>>,
  TError = ErrorResponse,
>(
  queryClient: QueryClient,
  id: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSingleQuiz>>, TError, TData>>
    request?: SecondParameter<typeof customFetch>
  },
): Promise<QueryClient> => {
  const queryOptions = getGetSingleQuizQueryOptions(id, options)

  await queryClient.prefetchQuery(queryOptions)

  return queryClient
}

export type updateQuizResponse200 = {
  data: QuizEntity
  status: 200
}

export type updateQuizResponse401 = {
  data: ErrorResponse
  status: 401
}

export type updateQuizResponse403 = {
  data: ErrorResponse
  status: 403
}

export type updateQuizResponse404 = {
  data: ErrorResponse
  status: 404
}

export type updateQuizResponse422 = {
  data: ErrorResponse
  status: 422
}

export type updateQuizResponse500 = {
  data: ErrorResponse
  status: 500
}

export type updateQuizResponseSuccess = updateQuizResponse200 & {
  headers: Headers
}
export type updateQuizResponseError = (
  | updateQuizResponse401
  | updateQuizResponse403
  | updateQuizResponse404
  | updateQuizResponse422
  | updateQuizResponse500
) & {
  headers: Headers
}

export type updateQuizResponse = updateQuizResponseSuccess | updateQuizResponseError

export const getUpdateQuizUrl = (id: number) => {
  return `/quizzes/${id}`
}

/**
 * @summary update a quiz
 */
export const updateQuiz = async (
  id: number,
  updateQuizDto: UpdateQuizDto,
  options?: RequestInit,
): Promise<updateQuizResponse> => {
  return customFetch<updateQuizResponse>(getUpdateQuizUrl(id), {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateQuizDto),
  })
}

export const getUpdateQuizMutationOptions = <TError = ErrorResponse, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateQuiz>>,
    TError,
    { id: number; data: UpdateQuizDto },
    TContext
  >
  request?: SecondParameter<typeof customFetch>
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateQuiz>>,
  TError,
  { id: number; data: UpdateQuizDto },
  TContext
> => {
  const mutationKey = ['updateQuiz']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateQuiz>>, { id: number; data: UpdateQuizDto }> = (
    props,
  ) => {
    const { id, data } = props ?? {}

    return updateQuiz(id, data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type UpdateQuizMutationResult = NonNullable<Awaited<ReturnType<typeof updateQuiz>>>
export type UpdateQuizMutationBody = UpdateQuizDto
export type UpdateQuizMutationError = ErrorResponse

/**
 * @summary update a quiz
 */
export const useUpdateQuiz = <TError = ErrorResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateQuiz>>,
      TError,
      { id: number; data: UpdateQuizDto },
      TContext
    >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof updateQuiz>>, TError, { id: number; data: UpdateQuizDto }, TContext> => {
  return useMutation(getUpdateQuizMutationOptions(options), queryClient)
}
export type deleteQuizResponse200 = {
  data: void
  status: 200
}

export type deleteQuizResponse401 = {
  data: ErrorResponse
  status: 401
}

export type deleteQuizResponse403 = {
  data: ErrorResponse
  status: 403
}

export type deleteQuizResponse404 = {
  data: ErrorResponse
  status: 404
}

export type deleteQuizResponse500 = {
  data: ErrorResponse
  status: 500
}

export type deleteQuizResponseSuccess = deleteQuizResponse200 & {
  headers: Headers
}
export type deleteQuizResponseError = (
  | deleteQuizResponse401
  | deleteQuizResponse403
  | deleteQuizResponse404
  | deleteQuizResponse500
) & {
  headers: Headers
}

export type deleteQuizResponse = deleteQuizResponseSuccess | deleteQuizResponseError

export const getDeleteQuizUrl = (id: number) => {
  return `/quizzes/${id}`
}

/**
 * @summary delete a quiz
 */
export const deleteQuiz = async (id: number, options?: RequestInit): Promise<deleteQuizResponse> => {
  return customFetch<deleteQuizResponse>(getDeleteQuizUrl(id), {
    ...options,
    method: 'DELETE',
  })
}

export const getDeleteQuizMutationOptions = <TError = ErrorResponse, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof deleteQuiz>>, TError, { id: number }, TContext>
  request?: SecondParameter<typeof customFetch>
}): UseMutationOptions<Awaited<ReturnType<typeof deleteQuiz>>, TError, { id: number }, TContext> => {
  const mutationKey = ['deleteQuiz']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteQuiz>>, { id: number }> = (props) => {
    const { id } = props ?? {}

    return deleteQuiz(id, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type DeleteQuizMutationResult = NonNullable<Awaited<ReturnType<typeof deleteQuiz>>>

export type DeleteQuizMutationError = ErrorResponse

/**
 * @summary delete a quiz
 */
export const useDeleteQuiz = <TError = ErrorResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof deleteQuiz>>, TError, { id: number }, TContext>
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof deleteQuiz>>, TError, { id: number }, TContext> => {
  return useMutation(getDeleteQuizMutationOptions(options), queryClient)
}
export type startQuizSessionResponse200 = {
  data: QuizSessionStateEntity
  status: 200
}

export type startQuizSessionResponse400 = {
  data: ErrorResponse
  status: 400
}

export type startQuizSessionResponse401 = {
  data: ErrorResponse
  status: 401
}

export type startQuizSessionResponse403 = {
  data: ErrorResponse
  status: 403
}

export type startQuizSessionResponse404 = {
  data: ErrorResponse
  status: 404
}

export type startQuizSessionResponse500 = {
  data: ErrorResponse
  status: 500
}

export type startQuizSessionResponseSuccess = startQuizSessionResponse200 & {
  headers: Headers
}
export type startQuizSessionResponseError = (
  | startQuizSessionResponse400
  | startQuizSessionResponse401
  | startQuizSessionResponse403
  | startQuizSessionResponse404
  | startQuizSessionResponse500
) & {
  headers: Headers
}

export type startQuizSessionResponse = startQuizSessionResponseSuccess | startQuizSessionResponseError

export const getStartQuizSessionUrl = (quizId: number) => {
  return `/quizzes/${quizId}/sessions`
}

/**
 * @summary start a new quiz session (or resume the active one) returns the current question
 */
export const startQuizSession = async (
  quizId: number,
  startQuizSessionDto: StartQuizSessionDto,
  options?: RequestInit,
): Promise<startQuizSessionResponse> => {
  return customFetch<startQuizSessionResponse>(getStartQuizSessionUrl(quizId), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(startQuizSessionDto),
  })
}

export const getStartQuizSessionMutationOptions = <TError = ErrorResponse, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof startQuizSession>>,
    TError,
    { quizId: number; data: StartQuizSessionDto },
    TContext
  >
  request?: SecondParameter<typeof customFetch>
}): UseMutationOptions<
  Awaited<ReturnType<typeof startQuizSession>>,
  TError,
  { quizId: number; data: StartQuizSessionDto },
  TContext
> => {
  const mutationKey = ['startQuizSession']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof startQuizSession>>,
    { quizId: number; data: StartQuizSessionDto }
  > = (props) => {
    const { quizId, data } = props ?? {}

    return startQuizSession(quizId, data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type StartQuizSessionMutationResult = NonNullable<Awaited<ReturnType<typeof startQuizSession>>>
export type StartQuizSessionMutationBody = StartQuizSessionDto
export type StartQuizSessionMutationError = ErrorResponse

/**
 * @summary start a new quiz session (or resume the active one) returns the current question
 */
export const useStartQuizSession = <TError = ErrorResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof startQuizSession>>,
      TError,
      { quizId: number; data: StartQuizSessionDto },
      TContext
    >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof startQuizSession>>,
  TError,
  { quizId: number; data: StartQuizSessionDto },
  TContext
> => {
  return useMutation(getStartQuizSessionMutationOptions(options), queryClient)
}
export type submitQuizSessionAnswerResponse200 = {
  data: QuizSessionStateEntity
  status: 200
}

export type submitQuizSessionAnswerResponse401 = {
  data: ErrorResponse
  status: 401
}

export type submitQuizSessionAnswerResponse404 = {
  data: ErrorResponse
  status: 404
}

export type submitQuizSessionAnswerResponse422 = {
  data: ErrorResponse
  status: 422
}

export type submitQuizSessionAnswerResponse500 = {
  data: ErrorResponse
  status: 500
}

export type submitQuizSessionAnswerResponseSuccess = submitQuizSessionAnswerResponse200 & {
  headers: Headers
}
export type submitQuizSessionAnswerResponseError = (
  | submitQuizSessionAnswerResponse401
  | submitQuizSessionAnswerResponse404
  | submitQuizSessionAnswerResponse422
  | submitQuizSessionAnswerResponse500
) & {
  headers: Headers
}

export type submitQuizSessionAnswerResponse =
  | submitQuizSessionAnswerResponseSuccess
  | submitQuizSessionAnswerResponseError

export const getSubmitQuizSessionAnswerUrl = (quizId: number) => {
  return `/quizzes/${quizId}/sessions/answer`
}

/**
 * @summary submit the user's answer for the current question and returns the next question (or the result once finished)
 */
export const submitQuizSessionAnswer = async (
  quizId: number,
  submitQuizSessionAnswerDto: SubmitQuizSessionAnswerDto,
  options?: RequestInit,
): Promise<submitQuizSessionAnswerResponse> => {
  return customFetch<submitQuizSessionAnswerResponse>(getSubmitQuizSessionAnswerUrl(quizId), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(submitQuizSessionAnswerDto),
  })
}

export const getSubmitQuizSessionAnswerMutationOptions = <TError = ErrorResponse, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof submitQuizSessionAnswer>>,
    TError,
    { quizId: number; data: SubmitQuizSessionAnswerDto },
    TContext
  >
  request?: SecondParameter<typeof customFetch>
}): UseMutationOptions<
  Awaited<ReturnType<typeof submitQuizSessionAnswer>>,
  TError,
  { quizId: number; data: SubmitQuizSessionAnswerDto },
  TContext
> => {
  const mutationKey = ['submitQuizSessionAnswer']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof submitQuizSessionAnswer>>,
    { quizId: number; data: SubmitQuizSessionAnswerDto }
  > = (props) => {
    const { quizId, data } = props ?? {}

    return submitQuizSessionAnswer(quizId, data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type SubmitQuizSessionAnswerMutationResult = NonNullable<Awaited<ReturnType<typeof submitQuizSessionAnswer>>>
export type SubmitQuizSessionAnswerMutationBody = SubmitQuizSessionAnswerDto
export type SubmitQuizSessionAnswerMutationError = ErrorResponse

/**
 * @summary submit the user's answer for the current question and returns the next question (or the result once finished)
 */
export const useSubmitQuizSessionAnswer = <TError = ErrorResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof submitQuizSessionAnswer>>,
      TError,
      { quizId: number; data: SubmitQuizSessionAnswerDto },
      TContext
    >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof submitQuizSessionAnswer>>,
  TError,
  { quizId: number; data: SubmitQuizSessionAnswerDto },
  TContext
> => {
  return useMutation(getSubmitQuizSessionAnswerMutationOptions(options), queryClient)
}
