/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Quiziset API
 * The RESTful APIs Docs for the Quiziset app
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query'

import type { ErrorResponse, UploadBodyDto, UploadResponse } from './model'

import { customFetch } from '../utils/orval-custom-fetch'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

export type uploadResponse201 = {
  data: UploadResponse
  status: 201
}

export type uploadResponse422 = {
  data: ErrorResponse
  status: 422
}

export type uploadResponse500 = {
  data: ErrorResponse
  status: 500
}

export type uploadResponseSuccess = uploadResponse201 & {
  headers: Headers
}
export type uploadResponseError = (uploadResponse422 | uploadResponse500) & {
  headers: Headers
}

export type uploadResponse = uploadResponseSuccess | uploadResponseError

export const getUploadUrl = (bucketName: 'quizzes' | 'profiles') => {
  return `/uploads/${bucketName}`
}

/**
 * @summary upload a file
 */
export const upload = async (
  bucketName: 'quizzes' | 'profiles',
  uploadBodyDto: UploadBodyDto,
  options?: RequestInit,
): Promise<uploadResponse> => {
  const formData = new FormData()
  formData.append(`file`, uploadBodyDto.file)

  return customFetch<uploadResponse>(getUploadUrl(bucketName), {
    ...options,
    method: 'POST',
    body: formData,
  })
}

export const getUploadMutationOptions = <TError = ErrorResponse, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof upload>>,
    TError,
    { bucketName: 'quizzes' | 'profiles'; data: UploadBodyDto },
    TContext
  >
  request?: SecondParameter<typeof customFetch>
}): UseMutationOptions<
  Awaited<ReturnType<typeof upload>>,
  TError,
  { bucketName: 'quizzes' | 'profiles'; data: UploadBodyDto },
  TContext
> => {
  const mutationKey = ['upload']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof upload>>,
    { bucketName: 'quizzes' | 'profiles'; data: UploadBodyDto }
  > = (props) => {
    const { bucketName, data } = props ?? {}

    return upload(bucketName, data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type UploadMutationResult = NonNullable<Awaited<ReturnType<typeof upload>>>
export type UploadMutationBody = UploadBodyDto
export type UploadMutationError = ErrorResponse

/**
 * @summary upload a file
 */
export const useUpload = <TError = ErrorResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof upload>>,
      TError,
      { bucketName: 'quizzes' | 'profiles'; data: UploadBodyDto },
      TContext
    >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof upload>>,
  TError,
  { bucketName: 'quizzes' | 'profiles'; data: UploadBodyDto },
  TContext
> => {
  return useMutation(getUploadMutationOptions(options), queryClient)
}
export type getFileResponse200 = {
  data: void
  status: 200
}

export type getFileResponse404 = {
  data: void
  status: 404
}

export type getFileResponse500 = {
  data: ErrorResponse
  status: 500
}

export type getFileResponseSuccess = getFileResponse200 & {
  headers: Headers
}
export type getFileResponseError = (getFileResponse404 | getFileResponse500) & {
  headers: Headers
}

export type getFileResponse = getFileResponseSuccess | getFileResponseError

export const getGetFileUrl = (bucketName: 'quizzes' | 'profiles', fileName: string) => {
  return `/uploads/${bucketName}/${fileName}`
}

/**
 * @summary returns file (e.g. image)
 */
export const getFile = async (
  bucketName: 'quizzes' | 'profiles',
  fileName: string,
  options?: RequestInit,
): Promise<getFileResponse> => {
  return customFetch<getFileResponse>(getGetFileUrl(bucketName, fileName), {
    ...options,
    method: 'GET',
  })
}

export const getGetFileQueryKey = (bucketName: 'quizzes' | 'profiles', fileName: string) => {
  return [`/uploads/${bucketName}/${fileName}`] as const
}

export const getGetFileQueryOptions = <TData = Awaited<ReturnType<typeof getFile>>, TError = void | ErrorResponse>(
  bucketName: 'quizzes' | 'profiles',
  fileName: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getFile>>, TError, TData>>
    request?: SecondParameter<typeof customFetch>
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetFileQueryKey(bucketName, fileName)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getFile>>> = ({ signal }) =>
    getFile(bucketName, fileName, { signal, ...requestOptions })

  return { queryKey, queryFn, enabled: !!(bucketName && fileName), ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getFile>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetFileQueryResult = NonNullable<Awaited<ReturnType<typeof getFile>>>
export type GetFileQueryError = void | ErrorResponse

export function useGetFile<TData = Awaited<ReturnType<typeof getFile>>, TError = void | ErrorResponse>(
  bucketName: 'quizzes' | 'profiles',
  fileName: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getFile>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<Awaited<ReturnType<typeof getFile>>, TError, Awaited<ReturnType<typeof getFile>>>,
        'initialData'
      >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetFile<TData = Awaited<ReturnType<typeof getFile>>, TError = void | ErrorResponse>(
  bucketName: 'quizzes' | 'profiles',
  fileName: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getFile>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<Awaited<ReturnType<typeof getFile>>, TError, Awaited<ReturnType<typeof getFile>>>,
        'initialData'
      >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetFile<TData = Awaited<ReturnType<typeof getFile>>, TError = void | ErrorResponse>(
  bucketName: 'quizzes' | 'profiles',
  fileName: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getFile>>, TError, TData>>
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary returns file (e.g. image)
 */

export function useGetFile<TData = Awaited<ReturnType<typeof getFile>>, TError = void | ErrorResponse>(
  bucketName: 'quizzes' | 'profiles',
  fileName: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getFile>>, TError, TData>>
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetFileQueryOptions(bucketName, fileName, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  return { ...query, queryKey: queryOptions.queryKey }
}

/**
 * @summary returns file (e.g. image)
 */
export const prefetchGetFileQuery = async <TData = Awaited<ReturnType<typeof getFile>>, TError = void | ErrorResponse>(
  queryClient: QueryClient,
  bucketName: 'quizzes' | 'profiles',
  fileName: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getFile>>, TError, TData>>
    request?: SecondParameter<typeof customFetch>
  },
): Promise<QueryClient> => {
  const queryOptions = getGetFileQueryOptions(bucketName, fileName, options)

  await queryClient.prefetchQuery(queryOptions)

  return queryClient
}
