/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Quiziset API
 * The RESTful APIs Docs for the Quiziset app
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query'

import type { UploadBodyDto, UploadResponse } from './model'

export type uploadResponse201 = {
  data: UploadResponse
  status: 201
}

export type uploadResponse422 = {
  data: void
  status: 422
}

export type uploadResponseSuccess = uploadResponse201 & {
  headers: Headers
}
export type uploadResponseError = uploadResponse422 & {
  headers: Headers
}

export const getUploadUrl = (bucketName: 'quizzes' | 'profiles') => {
  return `http://localhost:4004/uploads/${bucketName}`
}

/**
 * @summary upload a file
 */
export const upload = async (
  bucketName: 'quizzes' | 'profiles',
  uploadBodyDto: UploadBodyDto,
  options?: RequestInit,
): Promise<uploadResponseSuccess> => {
  const formData = new FormData()
  formData.append(`file`, uploadBodyDto.file)

  const res = await fetch(getUploadUrl(bucketName), {
    ...options,
    method: 'POST',
    body: formData,
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  if (!res.ok) {
    const err: globalThis.Error & { info?: uploadResponseError['data']; status?: number } = new globalThis.Error()
    const data: uploadResponseError['data'] = body ? JSON.parse(body) : {}
    err.info = data
    err.status = res.status
    throw err
  }
  const data: uploadResponseSuccess['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as uploadResponseSuccess
}

export const getUploadMutationOptions = <TError = void, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof upload>>,
    TError,
    { bucketName: 'quizzes' | 'profiles'; data: UploadBodyDto },
    TContext
  >
  fetch?: RequestInit
}): UseMutationOptions<
  Awaited<ReturnType<typeof upload>>,
  TError,
  { bucketName: 'quizzes' | 'profiles'; data: UploadBodyDto },
  TContext
> => {
  const mutationKey = ['upload']
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof upload>>,
    { bucketName: 'quizzes' | 'profiles'; data: UploadBodyDto }
  > = (props) => {
    const { bucketName, data } = props ?? {}

    return upload(bucketName, data, fetchOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type UploadMutationResult = NonNullable<Awaited<ReturnType<typeof upload>>>
export type UploadMutationBody = UploadBodyDto
export type UploadMutationError = void

/**
 * @summary upload a file
 */
export const useUpload = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof upload>>,
      TError,
      { bucketName: 'quizzes' | 'profiles'; data: UploadBodyDto },
      TContext
    >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof upload>>,
  TError,
  { bucketName: 'quizzes' | 'profiles'; data: UploadBodyDto },
  TContext
> => {
  return useMutation(getUploadMutationOptions(options), queryClient)
}
export type getFileResponse200 = {
  data: void
  status: 200
}

export type getFileResponse404 = {
  data: void
  status: 404
}

export type getFileResponseSuccess = getFileResponse200 & {
  headers: Headers
}
export type getFileResponseError = getFileResponse404 & {
  headers: Headers
}

export const getGetFileUrl = (bucketName: 'quizzes' | 'profiles', fileName: string) => {
  return `http://localhost:4004/uploads/${bucketName}/${fileName}`
}

/**
 * @summary returns file (e.g. image)
 */
export const getFile = async (
  bucketName: 'quizzes' | 'profiles',
  fileName: string,
  options?: RequestInit,
): Promise<getFileResponseSuccess> => {
  const res = await fetch(getGetFileUrl(bucketName, fileName), {
    ...options,
    method: 'GET',
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  if (!res.ok) {
    const err: globalThis.Error & { info?: getFileResponseError['data']; status?: number } = new globalThis.Error()
    const data: getFileResponseError['data'] = body ? JSON.parse(body) : {}
    err.info = data
    err.status = res.status
    throw err
  }
  const data: getFileResponseSuccess['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as getFileResponseSuccess
}

export const getGetFileQueryKey = (bucketName: 'quizzes' | 'profiles', fileName: string) => {
  return [`http://localhost:4004/uploads/${bucketName}/${fileName}`] as const
}

export const getGetFileQueryOptions = <TData = Awaited<ReturnType<typeof getFile>>, TError = void>(
  bucketName: 'quizzes' | 'profiles',
  fileName: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getFile>>, TError, TData>>
    fetch?: RequestInit
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetFileQueryKey(bucketName, fileName)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getFile>>> = ({ signal }) =>
    getFile(bucketName, fileName, { signal, ...fetchOptions })

  return { queryKey, queryFn, enabled: !!(bucketName && fileName), ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getFile>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetFileQueryResult = NonNullable<Awaited<ReturnType<typeof getFile>>>
export type GetFileQueryError = void

export function useGetFile<TData = Awaited<ReturnType<typeof getFile>>, TError = void>(
  bucketName: 'quizzes' | 'profiles',
  fileName: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getFile>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<Awaited<ReturnType<typeof getFile>>, TError, Awaited<ReturnType<typeof getFile>>>,
        'initialData'
      >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetFile<TData = Awaited<ReturnType<typeof getFile>>, TError = void>(
  bucketName: 'quizzes' | 'profiles',
  fileName: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getFile>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<Awaited<ReturnType<typeof getFile>>, TError, Awaited<ReturnType<typeof getFile>>>,
        'initialData'
      >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetFile<TData = Awaited<ReturnType<typeof getFile>>, TError = void>(
  bucketName: 'quizzes' | 'profiles',
  fileName: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getFile>>, TError, TData>>
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary returns file (e.g. image)
 */

export function useGetFile<TData = Awaited<ReturnType<typeof getFile>>, TError = void>(
  bucketName: 'quizzes' | 'profiles',
  fileName: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getFile>>, TError, TData>>
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetFileQueryOptions(bucketName, fileName, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  return { ...query, queryKey: queryOptions.queryKey }
}
