/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Quiziset API
 * The RESTful APIs Docs for the Quiziset app
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  MutationFunctionContext,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query'

import type { ErrorResponse, UpdateUserDto, UserEntity } from './model'

import { customFetch } from '../utils/orval-custom-fetch'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K }
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    })
  }
  return result
}

export type getMeResponse200 = {
  data: UserEntity
  status: 200
}

export type getMeResponse401 = {
  data: ErrorResponse
  status: 401
}

export type getMeResponse404 = {
  data: ErrorResponse
  status: 404
}

export type getMeResponse500 = {
  data: ErrorResponse
  status: 500
}

export type getMeResponseSuccess = getMeResponse200 & {
  headers: Headers
}
export type getMeResponseError = (getMeResponse401 | getMeResponse404 | getMeResponse500) & {
  headers: Headers
}

export type getMeResponse = getMeResponseSuccess | getMeResponseError

export const getGetMeUrl = () => {
  return `/users/me`
}

/**
 * @summary get the current user profile
 */
export const getMe = async (options?: RequestInit): Promise<getMeResponse> => {
  return customFetch<getMeResponse>(getGetMeUrl(), {
    ...options,
    method: 'GET',
  })
}

export const getGetMeQueryKey = () => {
  return [`/users/me`] as const
}

export const getGetMeQueryOptions = <TData = Awaited<ReturnType<typeof getMe>>, TError = ErrorResponse>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>>
  request?: SecondParameter<typeof customFetch>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetMeQueryKey()

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMe>>> = ({ signal }) => getMe({ signal, ...requestOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }
}

export type GetMeQueryResult = NonNullable<Awaited<ReturnType<typeof getMe>>>
export type GetMeQueryError = ErrorResponse

export function useGetMe<TData = Awaited<ReturnType<typeof getMe>>, TError = ErrorResponse>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<Awaited<ReturnType<typeof getMe>>, TError, Awaited<ReturnType<typeof getMe>>>,
        'initialData'
      >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMe<TData = Awaited<ReturnType<typeof getMe>>, TError = ErrorResponse>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<Awaited<ReturnType<typeof getMe>>, TError, Awaited<ReturnType<typeof getMe>>>,
        'initialData'
      >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMe<TData = Awaited<ReturnType<typeof getMe>>, TError = ErrorResponse>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>>
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary get the current user profile
 */

export function useGetMe<TData = Awaited<ReturnType<typeof getMe>>, TError = ErrorResponse>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>>
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetMeQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  return withQueryKey(query, queryOptions.queryKey)
}

/**
 * @summary get the current user profile
 */
export const prefetchGetMeQuery = async <TData = Awaited<ReturnType<typeof getMe>>, TError = ErrorResponse>(
  queryClient: QueryClient,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>>
    request?: SecondParameter<typeof customFetch>
  },
): Promise<QueryClient> => {
  const queryOptions = getGetMeQueryOptions(options)

  await queryClient.prefetchQuery(queryOptions)

  return queryClient
}

export type updateMeResponse200 = {
  data: UserEntity
  status: 200
}

export type updateMeResponse400 = {
  data: ErrorResponse
  status: 400
}

export type updateMeResponse401 = {
  data: ErrorResponse
  status: 401
}

export type updateMeResponse404 = {
  data: ErrorResponse
  status: 404
}

export type updateMeResponse422 = {
  data: ErrorResponse
  status: 422
}

export type updateMeResponse500 = {
  data: ErrorResponse
  status: 500
}

export type updateMeResponseSuccess = updateMeResponse200 & {
  headers: Headers
}
export type updateMeResponseError = (
  | updateMeResponse400
  | updateMeResponse401
  | updateMeResponse404
  | updateMeResponse422
  | updateMeResponse500
) & {
  headers: Headers
}

export type updateMeResponse = updateMeResponseSuccess | updateMeResponseError

export const getUpdateMeUrl = () => {
  return `/users/me`
}

/**
 * @summary update the current user profile
 */
export const updateMe = async (updateUserDto: UpdateUserDto, options?: RequestInit): Promise<updateMeResponse> => {
  return customFetch<updateMeResponse>(getUpdateMeUrl(), {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateUserDto),
  })
}

export const getUpdateMeMutationOptions = <TError = ErrorResponse, TContext = unknown>(
  queryClient: QueryClient,
  options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof updateMe>>, TError, { data: UpdateUserDto }, TContext>
    skipInvalidation?: boolean
    request?: SecondParameter<typeof customFetch>
  },
): UseMutationOptions<Awaited<ReturnType<typeof updateMe>>, TError, { data: UpdateUserDto }, TContext> => {
  const mutationKey = ['updateMe']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateMe>>, { data: UpdateUserDto }> = (props) => {
    const { data } = props ?? {}

    return updateMe(data, requestOptions)
  }

  const onSuccess = (
    data: Awaited<ReturnType<typeof updateMe>>,
    variables: { data: UpdateUserDto },
    onMutateResult: TContext,
    context: MutationFunctionContext,
  ) => {
    if (!options?.skipInvalidation) {
      queryClient.invalidateQueries({ queryKey: getGetMeQueryKey() })
    }
    mutationOptions?.onSuccess?.(data, variables, onMutateResult, context)
  }

  return { ...mutationOptions, mutationFn, onSuccess }
}

export type UpdateMeMutationResult = NonNullable<Awaited<ReturnType<typeof updateMe>>>
export type UpdateMeMutationBody = UpdateUserDto
export type UpdateMeMutationError = ErrorResponse

/**
 * @summary update the current user profile
 */
export const useUpdateMe = <TError = ErrorResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof updateMe>>, TError, { data: UpdateUserDto }, TContext>
    skipInvalidation?: boolean
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof updateMe>>, TError, { data: UpdateUserDto }, TContext> => {
  const backupQueryClient = useQueryClient()
  return useMutation(getUpdateMeMutationOptions(queryClient ?? backupQueryClient, options), queryClient)
}
