/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Quiziset API
 * The RESTful APIs Docs for the Quiziset app
 * OpenAPI spec version: 1.0
 */

export interface AnswerEntity {
  text: string
  /** provided for all question types except "question-reorder" */
  isCorrect?: boolean
  /** provided for "question-cards" only */
  imageUrl?: string
}
