/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Quiziset API
 * The RESTful APIs Docs for the Quiziset app
 * OpenAPI spec version: 1.0
 */

export interface AnswerDto {
  text: string
  /** should be provided for all question (except question-reorder) */
  isCorrect?: boolean
  /** for "question-cards" it must be provided. otherwise, it must be omitted */
  imageUrl?: string
}
