/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Quiziset API
 * The RESTful APIs Docs for the Quiziset app
 * OpenAPI spec version: 1.0
 */

export interface AuthToken {
  /** JWT Auth Access Token */
  accessToken: string
}
