/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Quiziset API
 * The RESTful APIs Docs for the Quiziset app
 * OpenAPI spec version: 1.0
 */
import type { QuestionDto } from './question-dto'

export interface CreateQuizDto {
  title: string
  description: string
  imageUrl: string
  isPublic: boolean
  isAnalyticsEnabled: boolean
  questions: QuestionDto[]
}
