/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Quiziset API
 * The RESTful APIs Docs for the Quiziset app
 * OpenAPI spec version: 1.0
 */

export type GetSingleQuizFields = (typeof GetSingleQuizFields)[keyof typeof GetSingleQuizFields]

export const GetSingleQuizFields = {
  DETAILS: 'DETAILS',
  OVERVIEW: 'OVERVIEW',
} as const
