/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Quiziset API
 * The RESTful APIs Docs for the Quiziset app
 * OpenAPI spec version: 1.0
 */

export type GetAllQuizzesSortBy = (typeof GetAllQuizzesSortBy)[keyof typeof GetAllQuizzesSortBy]

export const GetAllQuizzesSortBy = {
  date: 'date',
  rating: 'rating',
  popularity: 'popularity',
  name: 'name',
} as const
