/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Quiziset API
 * The RESTful APIs Docs for the Quiziset app
 * OpenAPI spec version: 1.0
 */
import type { GetSingleQuizFields } from './get-single-quiz-fields'

export type GetSingleQuizParams = {
  /**
   * DETAILS: include questions (for quiz manager only). OVERVIEW: include wasTakenByCurrentUserAtLeastOnce & doesCurrentUserHaveActiveSession
   */
  fields?: GetSingleQuizFields
}
