/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Quiziset API
 * The RESTful APIs Docs for the Quiziset app
 * OpenAPI spec version: 1.0
 */

export type QuestionEntityQuestionType = (typeof QuestionEntityQuestionType)[keyof typeof QuestionEntityQuestionType]

export const QuestionEntityQuestionType = {
  'question-checkbox': 'question-checkbox',
  'question-radio': 'question-radio',
  'question-reorder': 'question-reorder',
  'question-cards': 'question-cards',
} as const
