/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Quiziset API
 * The RESTful APIs Docs for the Quiziset app
 * OpenAPI spec version: 1.0
 */

export type QuestionDtoQuestionType = (typeof QuestionDtoQuestionType)[keyof typeof QuestionDtoQuestionType]

export const QuestionDtoQuestionType = {
  'question-checkbox': 'question-checkbox',
  'question-radio': 'question-radio',
  'question-reorder': 'question-reorder',
  'question-cards': 'question-cards',
} as const
