/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Quiziset API
 * The RESTful APIs Docs for the Quiziset app
 * OpenAPI spec version: 1.0
 */
import type { AnswerEntity } from './answer-entity'
import type { QuestionEntityQuestionType } from './question-entity-question-type'

export interface QuestionEntity {
  title: string
  questionType: QuestionEntityQuestionType
  answers: AnswerEntity[]
}
