/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Quiziset API
 * The RESTful APIs Docs for the Quiziset app
 * OpenAPI spec version: 1.0
 */
import type { AnswerDto } from './answer-dto'
import type { QuestionDtoQuestionType } from './question-dto-question-type'

export interface QuestionDto {
  title: string
  questionType: QuestionDtoQuestionType
  answers: AnswerDto[]
}
