/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Quiziset API
 * The RESTful APIs Docs for the Quiziset app
 * OpenAPI spec version: 1.0
 */
import type { QuestionEntity } from './question-entity'

export interface QuizEntity {
  id: number
  title: string
  description: string
  /**
   * quiz duration in minutes (null when there is no time limit)
   * @nullable
   */
  timeDurationInMinutes: number | null
  imageUrl: string
  isPublic: boolean
  isAnalyticsEnabled: boolean
  /** average of all review ratings (0 when there are no reviews yet) */
  averageRating: number
  /** indicates how many times the quiz was finished by all quiz takers. (info: if same user finish same quiz multiple times then every finish is counted) */
  totalFinishes: number
  /** returned only when querying a single quiz (with ?fields=DETAILS) AND if the current user is the quiz manager */
  questions?: QuestionEntity[]
  /** returned only when querying a single quiz (with ?fields=OVERVIEW) */
  wasTakenByCurrentUserAtLeastOnce?: boolean
  /** returned only when querying a single quiz (with ?fields=OVERVIEW) */
  doesCurrentUserHaveActiveSession?: boolean
  managerId: number
  createdAt: string
  updatedAt: string
}
