/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Quiziset API
 * The RESTful APIs Docs for the Quiziset app
 * OpenAPI spec version: 1.0
 */
import type { QuizSessionAnswerEntity } from './quiz-session-answer-entity'
import type { QuizSessionQuestionEntityQuestionType } from './quiz-session-question-entity-question-type'

export interface QuizSessionQuestionEntity {
  title: string
  questionType: QuizSessionQuestionEntityQuestionType
  answers: QuizSessionAnswerEntity[]
}
