/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Quiziset API
 * The RESTful APIs Docs for the Quiziset app
 * OpenAPI spec version: 1.0
 */
import type { QuizSessionQuestionEntity } from './quiz-session-question-entity'

export interface QuizSessionStateEntity {
  sessionId: number
  questionsCount: number
  currentQuestionIndex: number
  /**
   * null when the quiz has no time limit
   * @nullable
   */
  expireTime: string | null
  /** true once the quiz is finished (in this case "successfulAnswersCount" is returned) */
  isFinished: boolean
  /** the current question to answer (omitted once the quiz is finished) */
  currentQuestion?: QuizSessionQuestionEntity
  /** number of correctly answered questions (returned only once finished) */
  successfulAnswersCount?: number
}
