/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Quiziset API
 * The RESTful APIs Docs for the Quiziset app
 * OpenAPI spec version: 1.0
 */

export interface ReviewEntity {
  id: number
  /**
   * star rating from 1 to 5 (whole stars only)
   * @minimum 1
   * @maximum 5
   */
  rating: number
  /** @nullable */
  comment: string | null
  /** display name of the review author */
  authorName: string
  /** true when this review belongs to the current (authenticated) user */
  isMine: boolean
  createdAt: string
  updatedAt: string
}
