/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Quiziset API
 * The RESTful APIs Docs for the Quiziset app
 * OpenAPI spec version: 1.0
 */

export interface SignupDto {
  /** name length must be between 2 and 64 characters */
  name: string
  /** A valid email address (max length: 255) */
  email: string
  /** Password length must be 8 at least */
  password: string
}
