/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Quiziset API
 * The RESTful APIs Docs for the Quiziset app
 * OpenAPI spec version: 1.0
 */

export interface StartQuizSessionDto {
  /** must be true to start a session when the quiz has analytics enabled (otherwise a 400 bad request error is returned) */
  isAnalyticsShared?: boolean
}
