/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Quiziset API
 * The RESTful APIs Docs for the Quiziset app
 * OpenAPI spec version: 1.0
 */

export interface SubmitQuizSessionAnswerDto {
  /** indexes of the chosen answers for the current question. For "question-reorder" it is the answers arranged in the chosen order (order matters). For the other question types it is the set of selected answers (order is ignored) */
  answerIndexes: number[]
}
