/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Quiziset API
 * The RESTful APIs Docs for the Quiziset app
 * OpenAPI spec version: 1.0
 */

export interface UpdateUserDto {
  /** name length must be between 2 and 64 characters */
  name?: string
  /** a valid email address (max length: 255) */
  email?: string
  /**
   * a local image path (starts with /uploads or /public) or null to remove the image
   * @nullable
   */
  imageUrl?: string | null
}
