/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Quiziset API
 * The RESTful APIs Docs for the Quiziset app
 * OpenAPI spec version: 1.0
 */

export type GetQuizAnalyticsParams = {
  /**
   * page number (1-based)
   * @minimum 1
   */
  page?: number
  /**
   * results per page (allowed values 10 20 30 50)
   */
  pageSize?: number
}
