/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Quiziset API
 * The RESTful APIs Docs for the Quiziset app
 * OpenAPI spec version: 1.0
 */
import type { QuizEntity } from './quiz-entity'

export interface PaginatedQuizzesEntity {
  data: QuizEntity[]
  /** current page (1-based) */
  page: number
  /** number of items per page */
  pageSize: number
  /** total number of quizzes matching the query (across all pages) */
  totalMatches: number
  /** total number of pages */
  totalPages: number
}
