/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Quiziset API
 * The RESTful APIs Docs for the Quiziset app
 * OpenAPI spec version: 1.0
 */

export interface PasswordResetRequestResponse {
  /** link to the mailcatcher web UI so the email can be opened easily (only returned in development only it is empty in production) */
  previewUrl?: string
}
