/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Quiziset API
 * The RESTful APIs Docs for the Quiziset app
 * OpenAPI spec version: 1.0
 */
import type { PublicUserEntity } from './public-user-entity'
import type { QuestionEntity } from './question-entity'

export interface QuizEntity {
  id: number
  title: string
  description: string
  /**
   * quiz duration in minutes (null when there is no time limit)
   * @nullable
   */
  timeDurationInMinutes: number | null
  imageUrl: string
  isPublic: boolean
  isAnalyticsEnabled: boolean
  /** average of all quiz review ratings (0 when there are no reviews yet) */
  averageRating: number
  /** indicates how many times the quiz was finished by all quiz takers. (info: if same user finish same quiz multiple times then every finish is counted) */
  totalFinishes: number
  /** returned only when querying a single quiz (with ?fields=DETAILS) AND if the current user is the quiz manager */
  questions?: QuestionEntity[]
  /** returned only when querying a single quiz (with ?fields=OVERVIEW) */
  wasTakenByCurrentUserAtLeastOnce?: boolean
  /** returned only when querying a single quiz (with ?fields=OVERVIEW) */
  doesCurrentUserHaveActiveSession?: boolean
  /** whether the current (authenticated) user has marked this quiz as favorite (btw it is always false for anonymous users) please keep in mind that this attr is returned for GET requests only (but not for create/update quiz requests) */
  isFavorite?: boolean
  managerId: number
  /** the quiz creator (returned for GET requests only but not for create/update quiz requests) */
  manager?: PublicUserEntity
  createdAt: string
  updatedAt: string
}
