/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Quiziset API
 * The RESTful APIs Docs for the Quiziset app
 * OpenAPI spec version: 1.0
 */

export interface ResetPasswordDto {
  /** the reset token from the emailed link */
  token: string
  /** Password length must be 8 at least */
  password: string
}
