/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Quiziset API
 * The RESTful APIs Docs for the Quiziset app
 * OpenAPI spec version: 1.0
 */

export interface UpdateReviewDto {
  /**
   * star rating from 1 to 5 (whole stars only)
   * @minimum 1
   * @maximum 5
   */
  rating?: number
  /** optional text comment (max 255 chars) */
  comment?: string
}
