/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Quiziset API
 * The RESTful APIs Docs for the Quiziset app
 * OpenAPI spec version: 1.0
 */
import { useMutation } from '@tanstack/react-query'
import type { MutationFunction, QueryClient, UseMutationOptions, UseMutationResult } from '@tanstack/react-query'

import type {
  AuthToken,
  ErrorResponse,
  LoginDto,
  PasswordResetRequestResponse,
  RequestPasswordResetDto,
  ResetPasswordDto,
  SignupDto,
} from './model'

import { customFetch } from '../utils/orval-custom-fetch/orval-custom-fetch'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

export type signupResponse201 = {
  data: AuthToken
  status: 201
}

export type signupResponse400 = {
  data: ErrorResponse
  status: 400
}

export type signupResponse422 = {
  data: ErrorResponse
  status: 422
}

export type signupResponse500 = {
  data: ErrorResponse
  status: 500
}

export type signupResponseSuccess = signupResponse201 & {
  headers: Headers
}
export type signupResponseError = (signupResponse400 | signupResponse422 | signupResponse500) & {
  headers: Headers
}

export type signupResponse = signupResponseSuccess | signupResponseError

export const getSignupUrl = () => {
  return `/auth/signup`
}

/**
 * @summary Registers a new user
 */
export const signup = async (signupDto: SignupDto, options?: RequestInit): Promise<signupResponse> => {
  return customFetch<signupResponse>(getSignupUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(signupDto),
  })
}

export const getSignupMutationOptions = <TError = ErrorResponse, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof signup>>, TError, { data: SignupDto }, TContext>
  request?: SecondParameter<typeof customFetch>
}): UseMutationOptions<Awaited<ReturnType<typeof signup>>, TError, { data: SignupDto }, TContext> => {
  const mutationKey = ['signup']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof signup>>, { data: SignupDto }> = (props) => {
    const { data } = props ?? {}

    return signup(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type SignupMutationResult = NonNullable<Awaited<ReturnType<typeof signup>>>
export type SignupMutationBody = SignupDto
export type SignupMutationError = ErrorResponse

/**
 * @summary Registers a new user
 */
export const useSignup = <TError = ErrorResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof signup>>, TError, { data: SignupDto }, TContext>
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof signup>>, TError, { data: SignupDto }, TContext> => {
  return useMutation(getSignupMutationOptions(options), queryClient)
}
export type loginResponse200 = {
  data: AuthToken
  status: 200
}

export type loginResponse400 = {
  data: ErrorResponse
  status: 400
}

export type loginResponse500 = {
  data: ErrorResponse
  status: 500
}

export type loginResponseSuccess = loginResponse200 & {
  headers: Headers
}
export type loginResponseError = (loginResponse400 | loginResponse500) & {
  headers: Headers
}

export type loginResponse = loginResponseSuccess | loginResponseError

export const getLoginUrl = () => {
  return `/auth/login`
}

/**
 * @summary Logins User
 */
export const login = async (loginDto: LoginDto, options?: RequestInit): Promise<loginResponse> => {
  return customFetch<loginResponse>(getLoginUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(loginDto),
  })
}

export const getLoginMutationOptions = <TError = ErrorResponse, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof login>>, TError, { data: LoginDto }, TContext>
  request?: SecondParameter<typeof customFetch>
}): UseMutationOptions<Awaited<ReturnType<typeof login>>, TError, { data: LoginDto }, TContext> => {
  const mutationKey = ['login']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof login>>, { data: LoginDto }> = (props) => {
    const { data } = props ?? {}

    return login(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type LoginMutationResult = NonNullable<Awaited<ReturnType<typeof login>>>
export type LoginMutationBody = LoginDto
export type LoginMutationError = ErrorResponse

/**
 * @summary Logins User
 */
export const useLogin = <TError = ErrorResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof login>>, TError, { data: LoginDto }, TContext>
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof login>>, TError, { data: LoginDto }, TContext> => {
  return useMutation(getLoginMutationOptions(options), queryClient)
}
export type requestPasswordResetResponse201 = {
  data: PasswordResetRequestResponse
  status: 201
}

export type requestPasswordResetResponse400 = {
  data: ErrorResponse
  status: 400
}

export type requestPasswordResetResponse422 = {
  data: ErrorResponse
  status: 422
}

export type requestPasswordResetResponse500 = {
  data: ErrorResponse
  status: 500
}

export type requestPasswordResetResponseSuccess = requestPasswordResetResponse201 & {
  headers: Headers
}
export type requestPasswordResetResponseError = (
  | requestPasswordResetResponse400
  | requestPasswordResetResponse422
  | requestPasswordResetResponse500
) & {
  headers: Headers
}

export type requestPasswordResetResponse = requestPasswordResetResponseSuccess | requestPasswordResetResponseError

export const getRequestPasswordResetUrl = () => {
  return `/auth/request-password-reset`
}

/**
 * @summary Sends a password reset email
 */
export const requestPasswordReset = async (
  requestPasswordResetDto: RequestPasswordResetDto,
  options?: RequestInit,
): Promise<requestPasswordResetResponse> => {
  return customFetch<requestPasswordResetResponse>(getRequestPasswordResetUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(requestPasswordResetDto),
  })
}

export const getRequestPasswordResetMutationOptions = <TError = ErrorResponse, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof requestPasswordReset>>,
    TError,
    { data: RequestPasswordResetDto },
    TContext
  >
  request?: SecondParameter<typeof customFetch>
}): UseMutationOptions<
  Awaited<ReturnType<typeof requestPasswordReset>>,
  TError,
  { data: RequestPasswordResetDto },
  TContext
> => {
  const mutationKey = ['requestPasswordReset']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof requestPasswordReset>>,
    { data: RequestPasswordResetDto }
  > = (props) => {
    const { data } = props ?? {}

    return requestPasswordReset(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type RequestPasswordResetMutationResult = NonNullable<Awaited<ReturnType<typeof requestPasswordReset>>>
export type RequestPasswordResetMutationBody = RequestPasswordResetDto
export type RequestPasswordResetMutationError = ErrorResponse

/**
 * @summary Sends a password reset email
 */
export const useRequestPasswordReset = <TError = ErrorResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof requestPasswordReset>>,
      TError,
      { data: RequestPasswordResetDto },
      TContext
    >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof requestPasswordReset>>,
  TError,
  { data: RequestPasswordResetDto },
  TContext
> => {
  return useMutation(getRequestPasswordResetMutationOptions(options), queryClient)
}
export type resetPasswordResponse201 = {
  data: AuthToken
  status: 201
}

export type resetPasswordResponse400 = {
  data: ErrorResponse
  status: 400
}

export type resetPasswordResponse422 = {
  data: ErrorResponse
  status: 422
}

export type resetPasswordResponse500 = {
  data: ErrorResponse
  status: 500
}

export type resetPasswordResponseSuccess = resetPasswordResponse201 & {
  headers: Headers
}
export type resetPasswordResponseError = (
  | resetPasswordResponse400
  | resetPasswordResponse422
  | resetPasswordResponse500
) & {
  headers: Headers
}

export type resetPasswordResponse = resetPasswordResponseSuccess | resetPasswordResponseError

export const getResetPasswordUrl = () => {
  return `/auth/reset-password`
}

/**
 * @summary Resets the password and logs the user in
 */
export const resetPassword = async (
  resetPasswordDto: ResetPasswordDto,
  options?: RequestInit,
): Promise<resetPasswordResponse> => {
  return customFetch<resetPasswordResponse>(getResetPasswordUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(resetPasswordDto),
  })
}

export const getResetPasswordMutationOptions = <TError = ErrorResponse, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof resetPassword>>, TError, { data: ResetPasswordDto }, TContext>
  request?: SecondParameter<typeof customFetch>
}): UseMutationOptions<Awaited<ReturnType<typeof resetPassword>>, TError, { data: ResetPasswordDto }, TContext> => {
  const mutationKey = ['resetPassword']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof resetPassword>>, { data: ResetPasswordDto }> = (
    props,
  ) => {
    const { data } = props ?? {}

    return resetPassword(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type ResetPasswordMutationResult = NonNullable<Awaited<ReturnType<typeof resetPassword>>>
export type ResetPasswordMutationBody = ResetPasswordDto
export type ResetPasswordMutationError = ErrorResponse

/**
 * @summary Resets the password and logs the user in
 */
export const useResetPassword = <TError = ErrorResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof resetPassword>>,
      TError,
      { data: ResetPasswordDto },
      TContext
    >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof resetPassword>>, TError, { data: ResetPasswordDto }, TContext> => {
  return useMutation(getResetPasswordMutationOptions(options), queryClient)
}
