/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Quiziset API
 * The RESTful APIs Docs for the Quiziset app
 * OpenAPI spec version: 1.0
 */
import { useQuery } from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query'

import type { ErrorResponse, GetQuizAnalyticsParams, PaginatedQuizAnalyticsEntity } from './model'

import { customFetch } from '../utils/orval-custom-fetch/orval-custom-fetch'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K }
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    })
  }
  return result
}

export type getQuizAnalyticsResponse200 = {
  data: PaginatedQuizAnalyticsEntity
  status: 200
}

export type getQuizAnalyticsResponse400 = {
  data: ErrorResponse
  status: 400
}

export type getQuizAnalyticsResponse401 = {
  data: ErrorResponse
  status: 401
}

export type getQuizAnalyticsResponse403 = {
  data: ErrorResponse
  status: 403
}

export type getQuizAnalyticsResponse404 = {
  data: ErrorResponse
  status: 404
}

export type getQuizAnalyticsResponse500 = {
  data: ErrorResponse
  status: 500
}

export type getQuizAnalyticsResponseSuccess = getQuizAnalyticsResponse200 & {
  headers: Headers
}
export type getQuizAnalyticsResponseError = (
  | getQuizAnalyticsResponse400
  | getQuizAnalyticsResponse401
  | getQuizAnalyticsResponse403
  | getQuizAnalyticsResponse404
  | getQuizAnalyticsResponse500
) & {
  headers: Headers
}

export type getQuizAnalyticsResponse = getQuizAnalyticsResponseSuccess | getQuizAnalyticsResponseError

export const getGetQuizAnalyticsUrl = (quizId: number, params?: GetQuizAnalyticsParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/quizzes/${quizId}/analytics?${stringifiedParams}`
    : `/quizzes/${quizId}/analytics`
}

/**
 * @summary list of the sessions that shared analytics for a quiz (this is accessible for quiz manager only)
 */
export const getQuizAnalytics = async (
  quizId: number,
  params?: GetQuizAnalyticsParams,
  options?: RequestInit,
): Promise<getQuizAnalyticsResponse> => {
  return customFetch<getQuizAnalyticsResponse>(getGetQuizAnalyticsUrl(quizId, params), {
    ...options,
    method: 'GET',
  })
}

export const getGetQuizAnalyticsQueryKey = (quizId: number, params?: GetQuizAnalyticsParams) => {
  return [`/quizzes/${quizId}/analytics`, ...(params ? [params] : [])] as const
}

export const getGetQuizAnalyticsQueryOptions = <
  TData = Awaited<ReturnType<typeof getQuizAnalytics>>,
  TError = ErrorResponse,
>(
  quizId: number,
  params?: GetQuizAnalyticsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getQuizAnalytics>>, TError, TData>>
    request?: SecondParameter<typeof customFetch>
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetQuizAnalyticsQueryKey(quizId, params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getQuizAnalytics>>> = ({ signal }) =>
    getQuizAnalytics(quizId, params, { signal, ...requestOptions })

  return { queryKey, queryFn, enabled: quizId !== null && quizId !== undefined, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getQuizAnalytics>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetQuizAnalyticsQueryResult = NonNullable<Awaited<ReturnType<typeof getQuizAnalytics>>>
export type GetQuizAnalyticsQueryError = ErrorResponse

export function useGetQuizAnalytics<TData = Awaited<ReturnType<typeof getQuizAnalytics>>, TError = ErrorResponse>(
  quizId: number,
  params: undefined | GetQuizAnalyticsParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getQuizAnalytics>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getQuizAnalytics>>,
          TError,
          Awaited<ReturnType<typeof getQuizAnalytics>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetQuizAnalytics<TData = Awaited<ReturnType<typeof getQuizAnalytics>>, TError = ErrorResponse>(
  quizId: number,
  params?: GetQuizAnalyticsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getQuizAnalytics>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getQuizAnalytics>>,
          TError,
          Awaited<ReturnType<typeof getQuizAnalytics>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetQuizAnalytics<TData = Awaited<ReturnType<typeof getQuizAnalytics>>, TError = ErrorResponse>(
  quizId: number,
  params?: GetQuizAnalyticsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getQuizAnalytics>>, TError, TData>>
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary list of the sessions that shared analytics for a quiz (this is accessible for quiz manager only)
 */

export function useGetQuizAnalytics<TData = Awaited<ReturnType<typeof getQuizAnalytics>>, TError = ErrorResponse>(
  quizId: number,
  params?: GetQuizAnalyticsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getQuizAnalytics>>, TError, TData>>
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetQuizAnalyticsQueryOptions(quizId, params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  return withQueryKey(query, queryOptions.queryKey)
}

/**
 * @summary list of the sessions that shared analytics for a quiz (this is accessible for quiz manager only)
 */
export const prefetchGetQuizAnalyticsQuery = async <
  TData = Awaited<ReturnType<typeof getQuizAnalytics>>,
  TError = ErrorResponse,
>(
  queryClient: QueryClient,
  quizId: number,
  params?: GetQuizAnalyticsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getQuizAnalytics>>, TError, TData>>
    request?: SecondParameter<typeof customFetch>
  },
): Promise<QueryClient> => {
  const queryOptions = getGetQuizAnalyticsQueryOptions(quizId, params, options)

  await queryClient.prefetchQuery(queryOptions)

  return queryClient
}
