/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Quiziset API
 * The RESTful APIs Docs for the Quiziset app
 * OpenAPI spec version: 1.0
 */
import { useMutation } from '@tanstack/react-query'
import type { MutationFunction, QueryClient, UseMutationOptions, UseMutationResult } from '@tanstack/react-query'

import type { ErrorResponse, QuizSessionStateEntity, StartQuizSessionDto, SubmitQuizSessionAnswerDto } from './model'

import { customFetch } from '../utils/orval-custom-fetch/orval-custom-fetch'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

export type startQuizSessionResponse200 = {
  data: QuizSessionStateEntity
  status: 200
}

export type startQuizSessionResponse400 = {
  data: ErrorResponse
  status: 400
}

export type startQuizSessionResponse401 = {
  data: ErrorResponse
  status: 401
}

export type startQuizSessionResponse403 = {
  data: ErrorResponse
  status: 403
}

export type startQuizSessionResponse404 = {
  data: ErrorResponse
  status: 404
}

export type startQuizSessionResponse500 = {
  data: ErrorResponse
  status: 500
}

export type startQuizSessionResponseSuccess = startQuizSessionResponse200 & {
  headers: Headers
}
export type startQuizSessionResponseError = (
  | startQuizSessionResponse400
  | startQuizSessionResponse401
  | startQuizSessionResponse403
  | startQuizSessionResponse404
  | startQuizSessionResponse500
) & {
  headers: Headers
}

export type startQuizSessionResponse = startQuizSessionResponseSuccess | startQuizSessionResponseError

export const getStartQuizSessionUrl = (quizId: number) => {
  return `/quizzes/${quizId}/sessions`
}

/**
 * @summary start a new quiz session (or resume the active one) returns the current question
 */
export const startQuizSession = async (
  quizId: number,
  startQuizSessionDto: StartQuizSessionDto,
  options?: RequestInit,
): Promise<startQuizSessionResponse> => {
  return customFetch<startQuizSessionResponse>(getStartQuizSessionUrl(quizId), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(startQuizSessionDto),
  })
}

export const getStartQuizSessionMutationOptions = <TError = ErrorResponse, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof startQuizSession>>,
    TError,
    { quizId: number; data: StartQuizSessionDto },
    TContext
  >
  request?: SecondParameter<typeof customFetch>
}): UseMutationOptions<
  Awaited<ReturnType<typeof startQuizSession>>,
  TError,
  { quizId: number; data: StartQuizSessionDto },
  TContext
> => {
  const mutationKey = ['startQuizSession']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof startQuizSession>>,
    { quizId: number; data: StartQuizSessionDto }
  > = (props) => {
    const { quizId, data } = props ?? {}

    return startQuizSession(quizId, data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type StartQuizSessionMutationResult = NonNullable<Awaited<ReturnType<typeof startQuizSession>>>
export type StartQuizSessionMutationBody = StartQuizSessionDto
export type StartQuizSessionMutationError = ErrorResponse

/**
 * @summary start a new quiz session (or resume the active one) returns the current question
 */
export const useStartQuizSession = <TError = ErrorResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof startQuizSession>>,
      TError,
      { quizId: number; data: StartQuizSessionDto },
      TContext
    >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof startQuizSession>>,
  TError,
  { quizId: number; data: StartQuizSessionDto },
  TContext
> => {
  return useMutation(getStartQuizSessionMutationOptions(options), queryClient)
}
export type submitQuizSessionAnswerResponse200 = {
  data: QuizSessionStateEntity
  status: 200
}

export type submitQuizSessionAnswerResponse401 = {
  data: ErrorResponse
  status: 401
}

export type submitQuizSessionAnswerResponse404 = {
  data: ErrorResponse
  status: 404
}

export type submitQuizSessionAnswerResponse422 = {
  data: ErrorResponse
  status: 422
}

export type submitQuizSessionAnswerResponse500 = {
  data: ErrorResponse
  status: 500
}

export type submitQuizSessionAnswerResponseSuccess = submitQuizSessionAnswerResponse200 & {
  headers: Headers
}
export type submitQuizSessionAnswerResponseError = (
  | submitQuizSessionAnswerResponse401
  | submitQuizSessionAnswerResponse404
  | submitQuizSessionAnswerResponse422
  | submitQuizSessionAnswerResponse500
) & {
  headers: Headers
}

export type submitQuizSessionAnswerResponse =
  | submitQuizSessionAnswerResponseSuccess
  | submitQuizSessionAnswerResponseError

export const getSubmitQuizSessionAnswerUrl = (quizId: number) => {
  return `/quizzes/${quizId}/sessions/answer`
}

/**
 * @summary submit the user's answer for the current question and returns the next question (or the result once finished)
 */
export const submitQuizSessionAnswer = async (
  quizId: number,
  submitQuizSessionAnswerDto: SubmitQuizSessionAnswerDto,
  options?: RequestInit,
): Promise<submitQuizSessionAnswerResponse> => {
  return customFetch<submitQuizSessionAnswerResponse>(getSubmitQuizSessionAnswerUrl(quizId), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(submitQuizSessionAnswerDto),
  })
}

export const getSubmitQuizSessionAnswerMutationOptions = <TError = ErrorResponse, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof submitQuizSessionAnswer>>,
    TError,
    { quizId: number; data: SubmitQuizSessionAnswerDto },
    TContext
  >
  request?: SecondParameter<typeof customFetch>
}): UseMutationOptions<
  Awaited<ReturnType<typeof submitQuizSessionAnswer>>,
  TError,
  { quizId: number; data: SubmitQuizSessionAnswerDto },
  TContext
> => {
  const mutationKey = ['submitQuizSessionAnswer']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof submitQuizSessionAnswer>>,
    { quizId: number; data: SubmitQuizSessionAnswerDto }
  > = (props) => {
    const { quizId, data } = props ?? {}

    return submitQuizSessionAnswer(quizId, data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type SubmitQuizSessionAnswerMutationResult = NonNullable<Awaited<ReturnType<typeof submitQuizSessionAnswer>>>
export type SubmitQuizSessionAnswerMutationBody = SubmitQuizSessionAnswerDto
export type SubmitQuizSessionAnswerMutationError = ErrorResponse

/**
 * @summary submit the user's answer for the current question and returns the next question (or the result once finished)
 */
export const useSubmitQuizSessionAnswer = <TError = ErrorResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof submitQuizSessionAnswer>>,
      TError,
      { quizId: number; data: SubmitQuizSessionAnswerDto },
      TContext
    >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof submitQuizSessionAnswer>>,
  TError,
  { quizId: number; data: SubmitQuizSessionAnswerDto },
  TContext
> => {
  return useMutation(getSubmitQuizSessionAnswerMutationOptions(options), queryClient)
}
