/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Quiziset API
 * The RESTful APIs Docs for the Quiziset app
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  MutationFunctionContext,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query'

import type {
  CreateQuizDto,
  ErrorResponse,
  GetAllQuizzesParams,
  GetSingleQuizParams,
  PaginatedQuizzesEntity,
  QuizEntity,
  UpdateQuizDto,
} from './model'

import { customFetch } from '../utils/orval-custom-fetch/orval-custom-fetch'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K }
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    })
  }
  return result
}

export type getAllQuizzesResponse200 = {
  data: PaginatedQuizzesEntity
  status: 200
}

export type getAllQuizzesResponse401 = {
  data: ErrorResponse
  status: 401
}

export type getAllQuizzesResponse500 = {
  data: ErrorResponse
  status: 500
}

export type getAllQuizzesResponseSuccess = getAllQuizzesResponse200 & {
  headers: Headers
}
export type getAllQuizzesResponseError = (getAllQuizzesResponse401 | getAllQuizzesResponse500) & {
  headers: Headers
}

export type getAllQuizzesResponse = getAllQuizzesResponseSuccess | getAllQuizzesResponseError

export const getGetAllQuizzesUrl = (params?: GetAllQuizzesParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0 ? `/quizzes?${stringifiedParams}` : `/quizzes`
}

/**
 * @summary get a paginated list of quizzes (public or managed/favorited by the current user) with optional search and sorting
 */
export const getAllQuizzes = async (
  params?: GetAllQuizzesParams,
  options?: RequestInit,
): Promise<getAllQuizzesResponse> => {
  return customFetch<getAllQuizzesResponse>(getGetAllQuizzesUrl(params), {
    ...options,
    method: 'GET',
  })
}

export const getGetAllQuizzesQueryKey = (params?: GetAllQuizzesParams) => {
  return [`/quizzes`, ...(params ? [params] : [])] as const
}

export const getGetAllQuizzesQueryOptions = <TData = Awaited<ReturnType<typeof getAllQuizzes>>, TError = ErrorResponse>(
  params?: GetAllQuizzesParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllQuizzes>>, TError, TData>>
    request?: SecondParameter<typeof customFetch>
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetAllQuizzesQueryKey(params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllQuizzes>>> = ({ signal }) =>
    getAllQuizzes(params, { signal, ...requestOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAllQuizzes>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAllQuizzesQueryResult = NonNullable<Awaited<ReturnType<typeof getAllQuizzes>>>
export type GetAllQuizzesQueryError = ErrorResponse

export function useGetAllQuizzes<TData = Awaited<ReturnType<typeof getAllQuizzes>>, TError = ErrorResponse>(
  params: undefined | GetAllQuizzesParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllQuizzes>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllQuizzes>>,
          TError,
          Awaited<ReturnType<typeof getAllQuizzes>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllQuizzes<TData = Awaited<ReturnType<typeof getAllQuizzes>>, TError = ErrorResponse>(
  params?: GetAllQuizzesParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllQuizzes>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllQuizzes>>,
          TError,
          Awaited<ReturnType<typeof getAllQuizzes>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllQuizzes<TData = Awaited<ReturnType<typeof getAllQuizzes>>, TError = ErrorResponse>(
  params?: GetAllQuizzesParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllQuizzes>>, TError, TData>>
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary get a paginated list of quizzes (public or managed/favorited by the current user) with optional search and sorting
 */

export function useGetAllQuizzes<TData = Awaited<ReturnType<typeof getAllQuizzes>>, TError = ErrorResponse>(
  params?: GetAllQuizzesParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllQuizzes>>, TError, TData>>
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetAllQuizzesQueryOptions(params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  return withQueryKey(query, queryOptions.queryKey)
}

/**
 * @summary get a paginated list of quizzes (public or managed/favorited by the current user) with optional search and sorting
 */
export const prefetchGetAllQuizzesQuery = async <
  TData = Awaited<ReturnType<typeof getAllQuizzes>>,
  TError = ErrorResponse,
>(
  queryClient: QueryClient,
  params?: GetAllQuizzesParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllQuizzes>>, TError, TData>>
    request?: SecondParameter<typeof customFetch>
  },
): Promise<QueryClient> => {
  const queryOptions = getGetAllQuizzesQueryOptions(params, options)

  await queryClient.prefetchQuery(queryOptions)

  return queryClient
}

export type createQuizResponse201 = {
  data: QuizEntity
  status: 201
}

export type createQuizResponse401 = {
  data: ErrorResponse
  status: 401
}

export type createQuizResponse422 = {
  data: ErrorResponse
  status: 422
}

export type createQuizResponse500 = {
  data: ErrorResponse
  status: 500
}

export type createQuizResponseSuccess = createQuizResponse201 & {
  headers: Headers
}
export type createQuizResponseError = (createQuizResponse401 | createQuizResponse422 | createQuizResponse500) & {
  headers: Headers
}

export type createQuizResponse = createQuizResponseSuccess | createQuizResponseError

export const getCreateQuizUrl = () => {
  return `/quizzes`
}

/**
 * @summary create a new quiz
 */
export const createQuiz = async (createQuizDto: CreateQuizDto, options?: RequestInit): Promise<createQuizResponse> => {
  return customFetch<createQuizResponse>(getCreateQuizUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createQuizDto),
  })
}

export const getCreateQuizMutationOptions = <TError = ErrorResponse, TContext = unknown>(
  queryClient: QueryClient,
  options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof createQuiz>>, TError, { data: CreateQuizDto }, TContext>
    skipInvalidation?: boolean
    request?: SecondParameter<typeof customFetch>
  },
): UseMutationOptions<Awaited<ReturnType<typeof createQuiz>>, TError, { data: CreateQuizDto }, TContext> => {
  const mutationKey = ['createQuiz']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof createQuiz>>, { data: CreateQuizDto }> = (props) => {
    const { data } = props ?? {}

    return createQuiz(data, requestOptions)
  }

  const onSuccess = (
    data: Awaited<ReturnType<typeof createQuiz>>,
    variables: { data: CreateQuizDto },
    onMutateResult: TContext,
    context: MutationFunctionContext,
  ) => {
    if (!options?.skipInvalidation) {
      queryClient.invalidateQueries({ queryKey: getGetAllQuizzesQueryKey() })
      queryClient.invalidateQueries({
        predicate: (query) => typeof query.queryKey[0] === 'string' && query.queryKey[0].startsWith('/quizzes/'),
      })
    }
    mutationOptions?.onSuccess?.(data, variables, onMutateResult, context)
  }

  return { ...mutationOptions, mutationFn, onSuccess }
}

export type CreateQuizMutationResult = NonNullable<Awaited<ReturnType<typeof createQuiz>>>
export type CreateQuizMutationBody = CreateQuizDto
export type CreateQuizMutationError = ErrorResponse

/**
 * @summary create a new quiz
 */
export const useCreateQuiz = <TError = ErrorResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof createQuiz>>, TError, { data: CreateQuizDto }, TContext>
    skipInvalidation?: boolean
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof createQuiz>>, TError, { data: CreateQuizDto }, TContext> => {
  const backupQueryClient = useQueryClient()
  return useMutation(getCreateQuizMutationOptions(queryClient ?? backupQueryClient, options), queryClient)
}
export type getSingleQuizResponse200 = {
  data: QuizEntity
  status: 200
}

export type getSingleQuizResponse403 = {
  data: ErrorResponse
  status: 403
}

export type getSingleQuizResponse404 = {
  data: ErrorResponse
  status: 404
}

export type getSingleQuizResponse500 = {
  data: ErrorResponse
  status: 500
}

export type getSingleQuizResponseSuccess = getSingleQuizResponse200 & {
  headers: Headers
}
export type getSingleQuizResponseError = (
  | getSingleQuizResponse403
  | getSingleQuizResponse404
  | getSingleQuizResponse500
) & {
  headers: Headers
}

export type getSingleQuizResponse = getSingleQuizResponseSuccess | getSingleQuizResponseError

export const getGetSingleQuizUrl = (id: number, params?: GetSingleQuizParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0 ? `/quizzes/${id}?${stringifiedParams}` : `/quizzes/${id}`
}

/**
 * @summary get a quiz by id
 */
export const getSingleQuiz = async (
  id: number,
  params?: GetSingleQuizParams,
  options?: RequestInit,
): Promise<getSingleQuizResponse> => {
  return customFetch<getSingleQuizResponse>(getGetSingleQuizUrl(id, params), {
    ...options,
    method: 'GET',
  })
}

export const getGetSingleQuizQueryKey = (id: number, params?: GetSingleQuizParams) => {
  return [`/quizzes/${id}`, ...(params ? [params] : [])] as const
}

export const getGetSingleQuizQueryOptions = <TData = Awaited<ReturnType<typeof getSingleQuiz>>, TError = ErrorResponse>(
  id: number,
  params?: GetSingleQuizParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSingleQuiz>>, TError, TData>>
    request?: SecondParameter<typeof customFetch>
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetSingleQuizQueryKey(id, params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getSingleQuiz>>> = ({ signal }) =>
    getSingleQuiz(id, params, { signal, ...requestOptions })

  return { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getSingleQuiz>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetSingleQuizQueryResult = NonNullable<Awaited<ReturnType<typeof getSingleQuiz>>>
export type GetSingleQuizQueryError = ErrorResponse

export function useGetSingleQuiz<TData = Awaited<ReturnType<typeof getSingleQuiz>>, TError = ErrorResponse>(
  id: number,
  params: undefined | GetSingleQuizParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSingleQuiz>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSingleQuiz>>,
          TError,
          Awaited<ReturnType<typeof getSingleQuiz>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSingleQuiz<TData = Awaited<ReturnType<typeof getSingleQuiz>>, TError = ErrorResponse>(
  id: number,
  params?: GetSingleQuizParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSingleQuiz>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSingleQuiz>>,
          TError,
          Awaited<ReturnType<typeof getSingleQuiz>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSingleQuiz<TData = Awaited<ReturnType<typeof getSingleQuiz>>, TError = ErrorResponse>(
  id: number,
  params?: GetSingleQuizParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSingleQuiz>>, TError, TData>>
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary get a quiz by id
 */

export function useGetSingleQuiz<TData = Awaited<ReturnType<typeof getSingleQuiz>>, TError = ErrorResponse>(
  id: number,
  params?: GetSingleQuizParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSingleQuiz>>, TError, TData>>
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetSingleQuizQueryOptions(id, params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  return withQueryKey(query, queryOptions.queryKey)
}

/**
 * @summary get a quiz by id
 */
export const prefetchGetSingleQuizQuery = async <
  TData = Awaited<ReturnType<typeof getSingleQuiz>>,
  TError = ErrorResponse,
>(
  queryClient: QueryClient,
  id: number,
  params?: GetSingleQuizParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSingleQuiz>>, TError, TData>>
    request?: SecondParameter<typeof customFetch>
  },
): Promise<QueryClient> => {
  const queryOptions = getGetSingleQuizQueryOptions(id, params, options)

  await queryClient.prefetchQuery(queryOptions)

  return queryClient
}

export type updateQuizResponse200 = {
  data: QuizEntity
  status: 200
}

export type updateQuizResponse401 = {
  data: ErrorResponse
  status: 401
}

export type updateQuizResponse403 = {
  data: ErrorResponse
  status: 403
}

export type updateQuizResponse404 = {
  data: ErrorResponse
  status: 404
}

export type updateQuizResponse422 = {
  data: ErrorResponse
  status: 422
}

export type updateQuizResponse500 = {
  data: ErrorResponse
  status: 500
}

export type updateQuizResponseSuccess = updateQuizResponse200 & {
  headers: Headers
}
export type updateQuizResponseError = (
  | updateQuizResponse401
  | updateQuizResponse403
  | updateQuizResponse404
  | updateQuizResponse422
  | updateQuizResponse500
) & {
  headers: Headers
}

export type updateQuizResponse = updateQuizResponseSuccess | updateQuizResponseError

export const getUpdateQuizUrl = (id: number) => {
  return `/quizzes/${id}`
}

/**
 * @summary update a quiz
 */
export const updateQuiz = async (
  id: number,
  updateQuizDto: UpdateQuizDto,
  options?: RequestInit,
): Promise<updateQuizResponse> => {
  return customFetch<updateQuizResponse>(getUpdateQuizUrl(id), {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateQuizDto),
  })
}

export const getUpdateQuizMutationOptions = <TError = ErrorResponse, TContext = unknown>(
  queryClient: QueryClient,
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateQuiz>>,
      TError,
      { id: number; data: UpdateQuizDto },
      TContext
    >
    skipInvalidation?: boolean
    request?: SecondParameter<typeof customFetch>
  },
): UseMutationOptions<
  Awaited<ReturnType<typeof updateQuiz>>,
  TError,
  { id: number; data: UpdateQuizDto },
  TContext
> => {
  const mutationKey = ['updateQuiz']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateQuiz>>, { id: number; data: UpdateQuizDto }> = (
    props,
  ) => {
    const { id, data } = props ?? {}

    return updateQuiz(id, data, requestOptions)
  }

  const onSuccess = (
    data: Awaited<ReturnType<typeof updateQuiz>>,
    variables: { id: number; data: UpdateQuizDto },
    onMutateResult: TContext,
    context: MutationFunctionContext,
  ) => {
    if (!options?.skipInvalidation) {
      queryClient.invalidateQueries({ queryKey: getGetAllQuizzesQueryKey() })
      queryClient.invalidateQueries({
        predicate: (query) => typeof query.queryKey[0] === 'string' && query.queryKey[0].startsWith('/quizzes/'),
      })
    }
    mutationOptions?.onSuccess?.(data, variables, onMutateResult, context)
  }

  return { ...mutationOptions, mutationFn, onSuccess }
}

export type UpdateQuizMutationResult = NonNullable<Awaited<ReturnType<typeof updateQuiz>>>
export type UpdateQuizMutationBody = UpdateQuizDto
export type UpdateQuizMutationError = ErrorResponse

/**
 * @summary update a quiz
 */
export const useUpdateQuiz = <TError = ErrorResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateQuiz>>,
      TError,
      { id: number; data: UpdateQuizDto },
      TContext
    >
    skipInvalidation?: boolean
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof updateQuiz>>, TError, { id: number; data: UpdateQuizDto }, TContext> => {
  const backupQueryClient = useQueryClient()
  return useMutation(getUpdateQuizMutationOptions(queryClient ?? backupQueryClient, options), queryClient)
}
export type deleteQuizResponse200 = {
  data: void
  status: 200
}

export type deleteQuizResponse401 = {
  data: ErrorResponse
  status: 401
}

export type deleteQuizResponse403 = {
  data: ErrorResponse
  status: 403
}

export type deleteQuizResponse404 = {
  data: ErrorResponse
  status: 404
}

export type deleteQuizResponse500 = {
  data: ErrorResponse
  status: 500
}

export type deleteQuizResponseSuccess = deleteQuizResponse200 & {
  headers: Headers
}
export type deleteQuizResponseError = (
  | deleteQuizResponse401
  | deleteQuizResponse403
  | deleteQuizResponse404
  | deleteQuizResponse500
) & {
  headers: Headers
}

export type deleteQuizResponse = deleteQuizResponseSuccess | deleteQuizResponseError

export const getDeleteQuizUrl = (id: number) => {
  return `/quizzes/${id}`
}

/**
 * @summary delete a quiz
 */
export const deleteQuiz = async (id: number, options?: RequestInit): Promise<deleteQuizResponse> => {
  return customFetch<deleteQuizResponse>(getDeleteQuizUrl(id), {
    ...options,
    method: 'DELETE',
  })
}

export const getDeleteQuizMutationOptions = <TError = ErrorResponse, TContext = unknown>(
  queryClient: QueryClient,
  options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof deleteQuiz>>, TError, { id: number }, TContext>
    skipInvalidation?: boolean
    request?: SecondParameter<typeof customFetch>
  },
): UseMutationOptions<Awaited<ReturnType<typeof deleteQuiz>>, TError, { id: number }, TContext> => {
  const mutationKey = ['deleteQuiz']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteQuiz>>, { id: number }> = (props) => {
    const { id } = props ?? {}

    return deleteQuiz(id, requestOptions)
  }

  const onSuccess = (
    data: Awaited<ReturnType<typeof deleteQuiz>>,
    variables: { id: number },
    onMutateResult: TContext,
    context: MutationFunctionContext,
  ) => {
    if (!options?.skipInvalidation) {
      queryClient.invalidateQueries({ queryKey: getGetAllQuizzesQueryKey() })
      queryClient.invalidateQueries({
        predicate: (query) => typeof query.queryKey[0] === 'string' && query.queryKey[0].startsWith('/quizzes/'),
      })
    }
    mutationOptions?.onSuccess?.(data, variables, onMutateResult, context)
  }

  return { ...mutationOptions, mutationFn, onSuccess }
}

export type DeleteQuizMutationResult = NonNullable<Awaited<ReturnType<typeof deleteQuiz>>>

export type DeleteQuizMutationError = ErrorResponse

/**
 * @summary delete a quiz
 */
export const useDeleteQuiz = <TError = ErrorResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof deleteQuiz>>, TError, { id: number }, TContext>
    skipInvalidation?: boolean
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof deleteQuiz>>, TError, { id: number }, TContext> => {
  const backupQueryClient = useQueryClient()
  return useMutation(getDeleteQuizMutationOptions(queryClient ?? backupQueryClient, options), queryClient)
}
export type addFavoriteResponse204 = {
  data: void
  status: 204
}

export type addFavoriteResponse401 = {
  data: ErrorResponse
  status: 401
}

export type addFavoriteResponse403 = {
  data: ErrorResponse
  status: 403
}

export type addFavoriteResponse404 = {
  data: ErrorResponse
  status: 404
}

export type addFavoriteResponse500 = {
  data: ErrorResponse
  status: 500
}

export type addFavoriteResponseSuccess = addFavoriteResponse204 & {
  headers: Headers
}
export type addFavoriteResponseError = (
  | addFavoriteResponse401
  | addFavoriteResponse403
  | addFavoriteResponse404
  | addFavoriteResponse500
) & {
  headers: Headers
}

export type addFavoriteResponse = addFavoriteResponseSuccess | addFavoriteResponseError

export const getAddFavoriteUrl = (quizId: number) => {
  return `/quizzes/${quizId}/favorite`
}

/**
 * @summary add the quiz to the current user favorites
 */
export const addFavorite = async (quizId: number, options?: RequestInit): Promise<addFavoriteResponse> => {
  return customFetch<addFavoriteResponse>(getAddFavoriteUrl(quizId), {
    ...options,
    method: 'POST',
  })
}

export const getAddFavoriteMutationOptions = <TError = ErrorResponse, TContext = unknown>(
  queryClient: QueryClient,
  options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof addFavorite>>, TError, { quizId: number }, TContext>
    skipInvalidation?: boolean
    request?: SecondParameter<typeof customFetch>
  },
): UseMutationOptions<Awaited<ReturnType<typeof addFavorite>>, TError, { quizId: number }, TContext> => {
  const mutationKey = ['addFavorite']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof addFavorite>>, { quizId: number }> = (props) => {
    const { quizId } = props ?? {}

    return addFavorite(quizId, requestOptions)
  }

  const onSuccess = (
    data: Awaited<ReturnType<typeof addFavorite>>,
    variables: { quizId: number },
    onMutateResult: TContext,
    context: MutationFunctionContext,
  ) => {
    if (!options?.skipInvalidation) {
      queryClient.invalidateQueries({ queryKey: getGetAllQuizzesQueryKey() })
      queryClient.invalidateQueries({
        predicate: (query) => typeof query.queryKey[0] === 'string' && query.queryKey[0].startsWith('/quizzes/'),
      })
    }
    mutationOptions?.onSuccess?.(data, variables, onMutateResult, context)
  }

  return { ...mutationOptions, mutationFn, onSuccess }
}

export type AddFavoriteMutationResult = NonNullable<Awaited<ReturnType<typeof addFavorite>>>

export type AddFavoriteMutationError = ErrorResponse

/**
 * @summary add the quiz to the current user favorites
 */
export const useAddFavorite = <TError = ErrorResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof addFavorite>>, TError, { quizId: number }, TContext>
    skipInvalidation?: boolean
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof addFavorite>>, TError, { quizId: number }, TContext> => {
  const backupQueryClient = useQueryClient()
  return useMutation(getAddFavoriteMutationOptions(queryClient ?? backupQueryClient, options), queryClient)
}
export type removeFavoriteResponse204 = {
  data: void
  status: 204
}

export type removeFavoriteResponse401 = {
  data: ErrorResponse
  status: 401
}

export type removeFavoriteResponse500 = {
  data: ErrorResponse
  status: 500
}

export type removeFavoriteResponseSuccess = removeFavoriteResponse204 & {
  headers: Headers
}
export type removeFavoriteResponseError = (removeFavoriteResponse401 | removeFavoriteResponse500) & {
  headers: Headers
}

export type removeFavoriteResponse = removeFavoriteResponseSuccess | removeFavoriteResponseError

export const getRemoveFavoriteUrl = (quizId: number) => {
  return `/quizzes/${quizId}/favorite`
}

/**
 * @summary remove the quiz from the current user favorites
 */
export const removeFavorite = async (quizId: number, options?: RequestInit): Promise<removeFavoriteResponse> => {
  return customFetch<removeFavoriteResponse>(getRemoveFavoriteUrl(quizId), {
    ...options,
    method: 'DELETE',
  })
}

export const getRemoveFavoriteMutationOptions = <TError = ErrorResponse, TContext = unknown>(
  queryClient: QueryClient,
  options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof removeFavorite>>, TError, { quizId: number }, TContext>
    skipInvalidation?: boolean
    request?: SecondParameter<typeof customFetch>
  },
): UseMutationOptions<Awaited<ReturnType<typeof removeFavorite>>, TError, { quizId: number }, TContext> => {
  const mutationKey = ['removeFavorite']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof removeFavorite>>, { quizId: number }> = (props) => {
    const { quizId } = props ?? {}

    return removeFavorite(quizId, requestOptions)
  }

  const onSuccess = (
    data: Awaited<ReturnType<typeof removeFavorite>>,
    variables: { quizId: number },
    onMutateResult: TContext,
    context: MutationFunctionContext,
  ) => {
    if (!options?.skipInvalidation) {
      queryClient.invalidateQueries({ queryKey: getGetAllQuizzesQueryKey() })
      queryClient.invalidateQueries({
        predicate: (query) => typeof query.queryKey[0] === 'string' && query.queryKey[0].startsWith('/quizzes/'),
      })
    }
    mutationOptions?.onSuccess?.(data, variables, onMutateResult, context)
  }

  return { ...mutationOptions, mutationFn, onSuccess }
}

export type RemoveFavoriteMutationResult = NonNullable<Awaited<ReturnType<typeof removeFavorite>>>

export type RemoveFavoriteMutationError = ErrorResponse

/**
 * @summary remove the quiz from the current user favorites
 */
export const useRemoveFavorite = <TError = ErrorResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof removeFavorite>>, TError, { quizId: number }, TContext>
    skipInvalidation?: boolean
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof removeFavorite>>, TError, { quizId: number }, TContext> => {
  const backupQueryClient = useQueryClient()
  return useMutation(getRemoveFavoriteMutationOptions(queryClient ?? backupQueryClient, options), queryClient)
}
