/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Quiziset API
 * The RESTful APIs Docs for the Quiziset app
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  MutationFunctionContext,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query'

import type { CreateReviewDto, ErrorResponse, ReviewEntity, UpdateReviewDto } from './model'

import { customFetch } from '../utils/orval-custom-fetch/orval-custom-fetch'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K }
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    })
  }
  return result
}

export type getQuizReviewsResponse200 = {
  data: ReviewEntity[]
  status: 200
}

export type getQuizReviewsResponse403 = {
  data: ErrorResponse
  status: 403
}

export type getQuizReviewsResponse404 = {
  data: ErrorResponse
  status: 404
}

export type getQuizReviewsResponse500 = {
  data: ErrorResponse
  status: 500
}

export type getQuizReviewsResponseSuccess = getQuizReviewsResponse200 & {
  headers: Headers
}
export type getQuizReviewsResponseError = (
  | getQuizReviewsResponse403
  | getQuizReviewsResponse404
  | getQuizReviewsResponse500
) & {
  headers: Headers
}

export type getQuizReviewsResponse = getQuizReviewsResponseSuccess | getQuizReviewsResponseError

export const getGetQuizReviewsUrl = (quizId: number) => {
  return `/quizzes/${quizId}/reviews`
}

/**
 * @summary list all reviews of a quiz
 */
export const getQuizReviews = async (quizId: number, options?: RequestInit): Promise<getQuizReviewsResponse> => {
  return customFetch<getQuizReviewsResponse>(getGetQuizReviewsUrl(quizId), {
    ...options,
    method: 'GET',
  })
}

export const getGetQuizReviewsQueryKey = (quizId: number) => {
  return [`/quizzes/${quizId}/reviews`] as const
}

export const getGetQuizReviewsQueryOptions = <
  TData = Awaited<ReturnType<typeof getQuizReviews>>,
  TError = ErrorResponse,
>(
  quizId: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getQuizReviews>>, TError, TData>>
    request?: SecondParameter<typeof customFetch>
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetQuizReviewsQueryKey(quizId)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getQuizReviews>>> = ({ signal }) =>
    getQuizReviews(quizId, { signal, ...requestOptions })

  return { queryKey, queryFn, enabled: quizId !== null && quizId !== undefined, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getQuizReviews>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetQuizReviewsQueryResult = NonNullable<Awaited<ReturnType<typeof getQuizReviews>>>
export type GetQuizReviewsQueryError = ErrorResponse

export function useGetQuizReviews<TData = Awaited<ReturnType<typeof getQuizReviews>>, TError = ErrorResponse>(
  quizId: number,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getQuizReviews>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getQuizReviews>>,
          TError,
          Awaited<ReturnType<typeof getQuizReviews>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetQuizReviews<TData = Awaited<ReturnType<typeof getQuizReviews>>, TError = ErrorResponse>(
  quizId: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getQuizReviews>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getQuizReviews>>,
          TError,
          Awaited<ReturnType<typeof getQuizReviews>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetQuizReviews<TData = Awaited<ReturnType<typeof getQuizReviews>>, TError = ErrorResponse>(
  quizId: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getQuizReviews>>, TError, TData>>
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary list all reviews of a quiz
 */

export function useGetQuizReviews<TData = Awaited<ReturnType<typeof getQuizReviews>>, TError = ErrorResponse>(
  quizId: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getQuizReviews>>, TError, TData>>
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetQuizReviewsQueryOptions(quizId, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  return withQueryKey(query, queryOptions.queryKey)
}

/**
 * @summary list all reviews of a quiz
 */
export const prefetchGetQuizReviewsQuery = async <
  TData = Awaited<ReturnType<typeof getQuizReviews>>,
  TError = ErrorResponse,
>(
  queryClient: QueryClient,
  quizId: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getQuizReviews>>, TError, TData>>
    request?: SecondParameter<typeof customFetch>
  },
): Promise<QueryClient> => {
  const queryOptions = getGetQuizReviewsQueryOptions(quizId, options)

  await queryClient.prefetchQuery(queryOptions)

  return queryClient
}

export type createReviewResponse201 = {
  data: ReviewEntity
  status: 201
}

export type createReviewResponse401 = {
  data: ErrorResponse
  status: 401
}

export type createReviewResponse403 = {
  data: ErrorResponse
  status: 403
}

export type createReviewResponse404 = {
  data: ErrorResponse
  status: 404
}

export type createReviewResponse422 = {
  data: ErrorResponse
  status: 422
}

export type createReviewResponse500 = {
  data: ErrorResponse
  status: 500
}

export type createReviewResponseSuccess = createReviewResponse201 & {
  headers: Headers
}
export type createReviewResponseError = (
  | createReviewResponse401
  | createReviewResponse403
  | createReviewResponse404
  | createReviewResponse422
  | createReviewResponse500
) & {
  headers: Headers
}

export type createReviewResponse = createReviewResponseSuccess | createReviewResponseError

export const getCreateReviewUrl = (quizId: number) => {
  return `/quizzes/${quizId}/reviews`
}

/**
 * @summary leave a review (only allowed once and only after finishing the quiz at least once)
 */
export const createReview = async (
  quizId: number,
  createReviewDto: CreateReviewDto,
  options?: RequestInit,
): Promise<createReviewResponse> => {
  return customFetch<createReviewResponse>(getCreateReviewUrl(quizId), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createReviewDto),
  })
}

export const getCreateReviewMutationOptions = <TError = ErrorResponse, TContext = unknown>(
  queryClient: QueryClient,
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createReview>>,
      TError,
      { quizId: number; data: CreateReviewDto },
      TContext
    >
    skipInvalidation?: boolean
    request?: SecondParameter<typeof customFetch>
  },
): UseMutationOptions<
  Awaited<ReturnType<typeof createReview>>,
  TError,
  { quizId: number; data: CreateReviewDto },
  TContext
> => {
  const mutationKey = ['createReview']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createReview>>,
    { quizId: number; data: CreateReviewDto }
  > = (props) => {
    const { quizId, data } = props ?? {}

    return createReview(quizId, data, requestOptions)
  }

  const onSuccess = (
    data: Awaited<ReturnType<typeof createReview>>,
    variables: { quizId: number; data: CreateReviewDto },
    onMutateResult: TContext,
    context: MutationFunctionContext,
  ) => {
    if (!options?.skipInvalidation) {
      queryClient.invalidateQueries({
        predicate: (query) => typeof query.queryKey[0] === 'string' && query.queryKey[0].startsWith('/quizzes/'),
      })
      queryClient.invalidateQueries({
        predicate: (query) => typeof query.queryKey[0] === 'string' && query.queryKey[0].startsWith('/quizzes/'),
      })
    }
    mutationOptions?.onSuccess?.(data, variables, onMutateResult, context)
  }

  return { ...mutationOptions, mutationFn, onSuccess }
}

export type CreateReviewMutationResult = NonNullable<Awaited<ReturnType<typeof createReview>>>
export type CreateReviewMutationBody = CreateReviewDto
export type CreateReviewMutationError = ErrorResponse

/**
 * @summary leave a review (only allowed once and only after finishing the quiz at least once)
 */
export const useCreateReview = <TError = ErrorResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createReview>>,
      TError,
      { quizId: number; data: CreateReviewDto },
      TContext
    >
    skipInvalidation?: boolean
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createReview>>,
  TError,
  { quizId: number; data: CreateReviewDto },
  TContext
> => {
  const backupQueryClient = useQueryClient()
  return useMutation(getCreateReviewMutationOptions(queryClient ?? backupQueryClient, options), queryClient)
}
export type updateReviewResponse200 = {
  data: ReviewEntity
  status: 200
}

export type updateReviewResponse401 = {
  data: ErrorResponse
  status: 401
}

export type updateReviewResponse403 = {
  data: ErrorResponse
  status: 403
}

export type updateReviewResponse404 = {
  data: ErrorResponse
  status: 404
}

export type updateReviewResponse422 = {
  data: ErrorResponse
  status: 422
}

export type updateReviewResponse500 = {
  data: ErrorResponse
  status: 500
}

export type updateReviewResponseSuccess = updateReviewResponse200 & {
  headers: Headers
}
export type updateReviewResponseError = (
  | updateReviewResponse401
  | updateReviewResponse403
  | updateReviewResponse404
  | updateReviewResponse422
  | updateReviewResponse500
) & {
  headers: Headers
}

export type updateReviewResponse = updateReviewResponseSuccess | updateReviewResponseError

export const getUpdateReviewUrl = (quizId: number, reviewId: number) => {
  return `/quizzes/${quizId}/reviews/${reviewId}`
}

/**
 * @summary update your own review
 */
export const updateReview = async (
  quizId: number,
  reviewId: number,
  updateReviewDto: UpdateReviewDto,
  options?: RequestInit,
): Promise<updateReviewResponse> => {
  return customFetch<updateReviewResponse>(getUpdateReviewUrl(quizId, reviewId), {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateReviewDto),
  })
}

export const getUpdateReviewMutationOptions = <TError = ErrorResponse, TContext = unknown>(
  queryClient: QueryClient,
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateReview>>,
      TError,
      { quizId: number; reviewId: number; data: UpdateReviewDto },
      TContext
    >
    skipInvalidation?: boolean
    request?: SecondParameter<typeof customFetch>
  },
): UseMutationOptions<
  Awaited<ReturnType<typeof updateReview>>,
  TError,
  { quizId: number; reviewId: number; data: UpdateReviewDto },
  TContext
> => {
  const mutationKey = ['updateReview']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateReview>>,
    { quizId: number; reviewId: number; data: UpdateReviewDto }
  > = (props) => {
    const { quizId, reviewId, data } = props ?? {}

    return updateReview(quizId, reviewId, data, requestOptions)
  }

  const onSuccess = (
    data: Awaited<ReturnType<typeof updateReview>>,
    variables: { quizId: number; reviewId: number; data: UpdateReviewDto },
    onMutateResult: TContext,
    context: MutationFunctionContext,
  ) => {
    if (!options?.skipInvalidation) {
      queryClient.invalidateQueries({
        predicate: (query) => typeof query.queryKey[0] === 'string' && query.queryKey[0].startsWith('/quizzes/'),
      })
      queryClient.invalidateQueries({
        predicate: (query) => typeof query.queryKey[0] === 'string' && query.queryKey[0].startsWith('/quizzes/'),
      })
    }
    mutationOptions?.onSuccess?.(data, variables, onMutateResult, context)
  }

  return { ...mutationOptions, mutationFn, onSuccess }
}

export type UpdateReviewMutationResult = NonNullable<Awaited<ReturnType<typeof updateReview>>>
export type UpdateReviewMutationBody = UpdateReviewDto
export type UpdateReviewMutationError = ErrorResponse

/**
 * @summary update your own review
 */
export const useUpdateReview = <TError = ErrorResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateReview>>,
      TError,
      { quizId: number; reviewId: number; data: UpdateReviewDto },
      TContext
    >
    skipInvalidation?: boolean
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateReview>>,
  TError,
  { quizId: number; reviewId: number; data: UpdateReviewDto },
  TContext
> => {
  const backupQueryClient = useQueryClient()
  return useMutation(getUpdateReviewMutationOptions(queryClient ?? backupQueryClient, options), queryClient)
}
export type deleteReviewResponse204 = {
  data: void
  status: 204
}

export type deleteReviewResponse401 = {
  data: ErrorResponse
  status: 401
}

export type deleteReviewResponse403 = {
  data: ErrorResponse
  status: 403
}

export type deleteReviewResponse404 = {
  data: ErrorResponse
  status: 404
}

export type deleteReviewResponse500 = {
  data: ErrorResponse
  status: 500
}

export type deleteReviewResponseSuccess = deleteReviewResponse204 & {
  headers: Headers
}
export type deleteReviewResponseError = (
  | deleteReviewResponse401
  | deleteReviewResponse403
  | deleteReviewResponse404
  | deleteReviewResponse500
) & {
  headers: Headers
}

export type deleteReviewResponse = deleteReviewResponseSuccess | deleteReviewResponseError

export const getDeleteReviewUrl = (quizId: number, reviewId: number) => {
  return `/quizzes/${quizId}/reviews/${reviewId}`
}

/**
 * @summary delete your own review
 */
export const deleteReview = async (
  quizId: number,
  reviewId: number,
  options?: RequestInit,
): Promise<deleteReviewResponse> => {
  return customFetch<deleteReviewResponse>(getDeleteReviewUrl(quizId, reviewId), {
    ...options,
    method: 'DELETE',
  })
}

export const getDeleteReviewMutationOptions = <TError = ErrorResponse, TContext = unknown>(
  queryClient: QueryClient,
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteReview>>,
      TError,
      { quizId: number; reviewId: number },
      TContext
    >
    skipInvalidation?: boolean
    request?: SecondParameter<typeof customFetch>
  },
): UseMutationOptions<
  Awaited<ReturnType<typeof deleteReview>>,
  TError,
  { quizId: number; reviewId: number },
  TContext
> => {
  const mutationKey = ['deleteReview']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteReview>>, { quizId: number; reviewId: number }> = (
    props,
  ) => {
    const { quizId, reviewId } = props ?? {}

    return deleteReview(quizId, reviewId, requestOptions)
  }

  const onSuccess = (
    data: Awaited<ReturnType<typeof deleteReview>>,
    variables: { quizId: number; reviewId: number },
    onMutateResult: TContext,
    context: MutationFunctionContext,
  ) => {
    if (!options?.skipInvalidation) {
      queryClient.invalidateQueries({
        predicate: (query) => typeof query.queryKey[0] === 'string' && query.queryKey[0].startsWith('/quizzes/'),
      })
      queryClient.invalidateQueries({
        predicate: (query) => typeof query.queryKey[0] === 'string' && query.queryKey[0].startsWith('/quizzes/'),
      })
    }
    mutationOptions?.onSuccess?.(data, variables, onMutateResult, context)
  }

  return { ...mutationOptions, mutationFn, onSuccess }
}

export type DeleteReviewMutationResult = NonNullable<Awaited<ReturnType<typeof deleteReview>>>

export type DeleteReviewMutationError = ErrorResponse

/**
 * @summary delete your own review
 */
export const useDeleteReview = <TError = ErrorResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteReview>>,
      TError,
      { quizId: number; reviewId: number },
      TContext
    >
    skipInvalidation?: boolean
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteReview>>,
  TError,
  { quizId: number; reviewId: number },
  TContext
> => {
  const backupQueryClient = useQueryClient()
  return useMutation(getDeleteReviewMutationOptions(queryClient ?? backupQueryClient, options), queryClient)
}
